### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by ihacku** [rednaga/APKiD#1]
rule jiangu : packer 

 $main_lib = "libjiagu.so"

jiangu -> jiagu

developed by Qihoo 360 http://jiagu.360.cn/

**Comment by CalebFenton** [comment]
Eagle eye, bruh. Thanks. Fixed in https://github.com/rednaga/APKiD/commit/88eeaf83593f640ca4fbdf9fdc21c3bae0ca3efa
