### ISSUE TITLE
AAMO "Malware obfuscator"

### ISSUE THREAD

**Issue by P0r0** [rednaga/APKiD#101]
src: [https://github.com/necst/aamo](https://github.com/necst/aamo)
A so called "malware obfuscator" that incudes the following features:

```
obfuscator_to_apply = [
    'Resigned',
    'Alignment',
    'Rebuild',
    'Fields',
    'Debug',
    'Indirections',
    'Defunct',
    'StringEncrypt',
    'Renaming',
    'Reordering',
    'Goto',
    'ArithmeticBranch',
    'Nop',
    'Asset',
    'Intercept',
    'Raw',
    'Resource',
    'Lib',
    'Restring',
    'Manifest',
    'Reflection']
```

Samples obfuscated and uploaded on koodous:
- App1: c1ef860af0e168f924663630ed3b61920b474d0c8b10e2bde6bfd3769dbd31a8
- App2: eb0d4e1ba2e880749594eb8739e65aa21b6f7b43798f04b6681065b396c15a78
- App3: b1e20bf3bdc53972424560e20c6d9ad12e5e47b8ed429a77f4ba5ff6cb92cb27
- App4: 82a570c272579aacdc22410e152f4519738f4e0ececa84e016201c33ad871fa6

The features that have  been enabled:
- App1: Fields renaming, String encryption, function renaming
- App2: String encryption, defunct, class renaming, nop, reordoring, goto
- App3: String encryption, defunct, class renaming, nop, reordoring, goto
- App4: Reordoring, goto, nop, arithmetic branches

**Comment by enovella** [comment]
Hi @P0r0,

As you've been messing around with it, do you see a unique fingerprint to target?

**Comment by P0r0** [comment]
Well..regarding the string encryption, may be by targeting the functions names "convertToString" and "getStorageEncryption".
![a](https://user-images.githubusercontent.com/40885652/42389404-e839ee18-8148-11e8-8336-15d3c1faa5d4.png)

**Comment by enovella** [comment]
Hi @P0r0,

first of all thanks for the elaborated post. Also, some remarks or ideas to your suggestions:

- Can you fingerprint feature by feature? I can imagine that some of them should be tough. However, you found a rule to hit all the samples using string encryption. The methods `convertToString` and `getStorageEncryption` are introduced by the obfuscator, aren't they? If so, you can write a rule using strings or opcodes. I would recommend you to use opcodes as in this rule https://github.com/enovella/APKiD/blob/master/apkid/rules/dex/packers.yara#L165. Let me know if you have any trouble.
- Regarding this picture showing fields and classes names, I'm afraid that they're randomized and thus cannot be targeted without hitting false positives. Can you spot something inserted by the obfuscator itself?

Cheers

**Comment by ismaelsilver** [comment]
Good evening, my friends, sorry to comment on this question, but it was the only pulse that I found it, I can not in any way overshadow my apk, I did everything in the script but it did not work. They could donate me, present the script of yours that is working or fix me to solve, excuse the writing

**Comment by P0r0** [comment]
@ismaelsilver sorry but I didn't understand anything about what you are asking for... :(

**Comment by enovella** [comment]
Didn't understand anything here sorry. Please rephrase again.
