### ISSUE TITLE
Can't detect upx

### ISSUE THREAD

**Issue by trisz404** [rednaga/APKiD#107]
upx packer is not detected.
[https://upx.github.io/](https://upx.github.io/)

**Comment by enovella** [comment]
Hi @trisz404,

what are you based on to claim isn't detected?  The `upx` rules are at https://github.com/rednaga/APKiD/blob/master/apkid/rules/elf/packers.yara#L77

Can you provide a sample which is not detected by APKiD?

Cheers

**Comment by CalebFenton** [comment]
I'm closing this for lack of info. Please feel free to re open once you have a hash or a sample or some vague clue.
