### ISSUE TITLE
(New) Secneo variant?

### ISSUE THREAD

**Issue by P0r0** [rednaga/APKiD#118]
In the current rule related to SecNeo, only "libDexHelper.so" and "libDexHelper-x86.so" are defined.

In the following samples (https://github.com/P0r0/apksamples/new_secneo), a new lib called "libdexjni.so" is used along with libDexHelper.so.

![a](https://user-images.githubusercontent.com/40885652/46153045-a7148400-c272-11e8-871f-56f22e742bfc.png)

![b](https://user-images.githubusercontent.com/40885652/46153054-abd93800-c272-11e8-9e1d-e9eee2a39925.png)

**Comment by enovella** [comment]
any news on this research? Could it be done before BlackHat Europe 2018? @P0r0

**Comment by CalebFenton** [comment]
Any chance of getting the sample or sample hash here?

**Comment by enovella** [comment]
@CalebFenton here https://github.com/P0r0/apksamples/tree/master/new_secneo

**Comment by strazzere** [comment]
Sometime between when this opened and now this has been solved.
