### ISSUE TITLE
Malicious sample core dumps APKiD

### ISSUE THREAD

**Issue by cryptax** [rednaga/APKiD#12]
This (malicious) sample crashes my instance of APKiD:
sha256: 21e291d1404646ca1fa2ce765e83bf527b9ce701f1bbae6c45b79f821fecfd1e

```bash
apkid 1224AB84.vpk
[!] APKiD 0.9.3 :: from RedNaga :: rednaga.io
[*] 1224AB84.vpk!classes.dex.bak
 |-> compiler : dexlib 1.x
Segmentation fault (core dumped)
```

Let me know if you need the core dump and/or the sample.

**Comment by CalebFenton** [comment]
I've tracked the issue down to the yara dex module. The dex file appears to be corrupt, e.g. dex checksums are wrong, the endian tag is wrong, etc. Even breaks 010 dex template. Does this file actually run? Regardless, apkid _should_ fail gracefully.

**Comment by CalebFenton** [comment]
Alright, I added some sanity checks for corrupt dex files which prevents the segfault for me, but should still allow obfuscated / offensive samples. Here's the change in the dex module: https://github.com/rednaga/yara/commit/c339fb761922ea6c3c2499c5249a14416d6a4ae2

**Comment by cryptax** [comment]
Confirms it works fine now:

```
$ apkid 1224AB84.vpk
[!] APKiD 0.9.4 :: from RedNaga :: rednaga.io
[*] 1224AB84.vpk!classes.dex.bak
 |-> compiler : dexlib 1.x
```
