### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by cryptax** [rednaga/APKiD#13]
For your information, I had several issues (again the same ones) upgrading APKiD. It's no big issue, because I fixed them and installed correctly, but just saying in case you can fix for a smoother install.
- In yara-python, I had to perform several fixes about those non C declarations. In yara/libyara/modules/pe.c and yara/libyara/rules.c:

``` C
for (int j = 0; j < pe->data_size % 4; j++)
```
- For some reason, I had yara_python-3.4.0.999-py2.7.egg-info and yara_python-3.5.0.999-py2.7.egg-info in /usr/local/lib/python2.7/dist-packages. Consequently, the install of APKiD failed with the message below (which is stupid because 3.5.0.999).

```
 Could not find a version that satisfies the requirement yara-python==3.5.0.999 (from apkid) (from versions: 3.4.0.0, 3.5.0)
No matching distribution found for yara-python==3.5.0.999 (from apkid)
```

Removing 3.4.0.999 fixed the issue in my case.

Cheers.

**Comment by CalebFenton** [comment]
I noticed that compilation works _fine_ on OSX when compiling yara itself, but when yara-python builds it, it uses a different compiler which is problematic. I had to patch yara in at least one other place also. Since I didn't change yara-python's build process, I have to assume it's a bug in yara-python. I'll look into it though, if at least to understand how it works.

Thanks, as always, for the detailed error reports.

**Comment by Lanchon** [comment]
and on ubuntu trusty...

```
$ python setup.py install

running install
running build
running build_ext
building 'yara' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara-python.c -o build/temp.linux-x86_64-2.7/yara-python.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/hex_grammar.c -o build/temp.linux-x86_64-2.7/yara/libyara/hex_grammar.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/hash.c -o build/temp.linux-x86_64-2.7/yara/libyara/hash.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/libyara.c -o build/temp.linux-x86_64-2.7/yara/libyara/libyara.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/re_lexer.c -o build/temp.linux-x86_64-2.7/yara/libyara/re_lexer.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/proc.c -o build/temp.linux-x86_64-2.7/yara/libyara/proc.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/rules.c -o build/temp.linux-x86_64-2.7/yara/libyara/rules.o
yara/libyara/rules.c: In function ‘yr_rules_save_stream’:
yara/libyara/rules.c:743:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
   ^
yara/libyara/rules.c:743:3: note: use option -std=c99 or -std=gnu99 to compile your code
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by cryptax** [comment]
@Lanchon For the compilation error you have, a workaround is to fix the code. You change the:
```
for (int i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
```
into
```
int i;
for (i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
```
and it will work.

**Comment by Lanchon** [comment]
yes i know! but the code is fine, the makefile has to be fixed

**Comment by cryptax** [comment]
no, the code is "not" fine. Declaring i in the loop is not "standard" C...
But this can probably be fixed in the Makefile too though.

-- Axelle.

**Comment by Lanchon** [comment]
yes, the code is totally fine! declaring variables mid-block and within for() constructs etc is standard C. those features were added first to GCC as extensions and then to the C language in working drafts a long while back. and then were finally ratified as standard in the previous century, lol. specifically in C99:
http://stackoverflow.com/questions/2321564/where-can-i-legally-declare-a-variable-in-c99

**Comment by Lanchon** [comment]
in GCC you have to enable the correct language dialect, either C99, or C99 with GNU extensions, or any later version. that's why the compiler spits:
`note: use option -std=c99 or -std=gnu99 to compile your code`

**Comment by Lanchon** [comment]
also,

> You change the:
```
for (int i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
```
> into
```
int i;
for (i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
```
> and it will work.

that is not entirely correct. older C dialects don't allow declaring variables mid-block, so the `int i;` up there is (depending on previous code) not real old-style C. it only worked for you because your GCC was probably configured to use C90 with GNU extensions by default, and among the GNU extensions there's the possibility of mid-block declarations. make GCC go for ANSI C and it will reject that code.

besides that, the semantics potentially change. with the `for(int i =...` construct, `i` goes out of scope as soon as the for ends, but not in your replacement. if the `i` identifier is referenced after the for, whatever outer-scope object that was referenced in the original code will be shadowed by the loop `i`, changing the meaning of the program, potentially silently.

for these two reasons, the correct replacement is:

```
{
  int i;
  for (i = 0; i < YR_BITARRAY_NCHARS(MAX_THREADS); ++i) {
  // ...
}
```

**Comment by arpit1997** [comment]
>in GCC you have to enable the correct language dialect, either C99, or C99 with GNU extensions, or any later version. that's why the compiler spits:
note: use option -std=c99 or -std=gnu99 to compile your code

Yeah its right
