### ISSUE TITLE
lib folder not present in cuckoo droid 2.0

### ISSUE THREAD

**Issue by jueemudras1** [rednaga/APKiD#137]
Hello sir,
I use the cuckoo sandbox for windows, it's work perfectly.
but when I am going to use cuckoo droid 2.0. I found "lib" folder is missing inside cuckoo droid.
without lib folder, we are not able to start the server.
kindly provided the folder so that we can use the cuckoo sandbox for android.

**Comment by strazzere** [comment]
Stale - not relevant to this actual project.
