### ISSUE TITLE
Crash on Secneh

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#138]
PR: https://github.com/rednaga/APKiD/pull/134

To be investigated:
```
>  apkid 0709d38575e15643f03793445479d869116dca319bce2296cb8af798453a8752.apk 
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] 0709d38575e15643f03793445479d869116dca319bce2296cb8af798453a8752.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] 0709d38575e15643f03793445479d869116dca319bce2296cb8af798453a8752.apk
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 11, in <module>
    load_entry_point('apkid==1.2.1', 'console_scripts', 'apkid')()
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.2.1-py2.7.egg/apkid/__init__.py", line 74, in main
    apkid.scan(input, args.timeout, args.json, args.output_dir, args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.2.1-py2.7.egg/apkid/apkid.py", line 88, in scan
    output.print_matches(file_path, matches)
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.2.1-py2.7.egg/apkid/output.py", line 45, in print_matches
    descriptions = ', '.join(sorted(matches[tags]))
TypeError: sequence item 0: expected string, yara.Match found
```

Am I the only one having this crash? @ulexec

**Comment by ulexec** [comment]
In line 81 at rules.py if I explicitly convert to str evert yara Match it works. 
`description = **str**(m.meta.get('description', m)**)**`
@CalebFenton @enovella let me know if this would work as a fix

**Comment by enovella** [comment]
Sounds good this fixes the issue. Only I'd love to know why it was crashing only with this sample. Some debugging should be required but I do not have much time now. Lets see what @CalebFenton says about it.

**Comment by CalebFenton** [comment]
Is there a file for reproducing the issue?

**Comment by enovella** [comment]
Here you go!
[0709d38575e15643f03793445479d869116dca319bce2296cb8af798453a8752.zip](https://github.com/rednaga/APKiD/files/2849498/0709d38575e15643f03793445479d869116dca319bce2296cb8af798453a8752.zip)

**Comment by ulexec** [comment]
@CalebFenton let us know how it goes. Maybe was my fault and I didnt write the signature properlly

**Comment by CalebFenton** [comment]
I think the problem is the rule has `decription` but it should be `description`.

**Comment by ulexec** [comment]
lmao. This is one hell of a  fail. will fix soon. thanks @CalebFenton

**Comment by enovella** [comment]
Good catch man!

**Comment by ulexec** [comment]
new pr fixing typo. sorry about that: https://github.com/rednaga/APKiD/pull/143

**Comment by CalebFenton** [comment]
@ulexec don't be so hard on yourself. It's an easy mistake to make. The real lesson here, I think, is to try not to settle for patches that seem to fix the issue without really understanding the cause.

These types of problems should be caught with tests and could be more obvious by using classes and type hinting instead of dicts.

**Comment by enovella** [comment]
Fixed in https://github.com/rednaga/APKiD/pull/143
