### ISSUE TITLE
New native packer used in BrawlStars

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#139]
Native packer with several layers of unpacking. Whitebox crypto, inline assembly syscalls, mmap-and-mprotect over and over.

**Info**: (@iGio90) http://www.giovanni-rocca.com/cracking-the-uncrackables-reverse-engineering-supercell-part-7/

![igio90-ismy-her0](https://user-images.githubusercontent.com/14809754/51948556-d570be80-2420-11e9-8420-d43d5f9da186.png)
![dugxvdvw4amk0iz](https://user-images.githubusercontent.com/14809754/51948509-b70ac300-2420-11e9-9e27-e1f117cf5606.jpg)
![dugvth_xcaassaz](https://user-images.githubusercontent.com/14809754/51948510-b70ac300-2420-11e9-847d-dac2f7985e74.jpg)
![duf31w-wsau8tqi](https://user-images.githubusercontent.com/14809754/51948511-b70ac300-2420-11e9-8e2c-fc7534926f6f.jpg)

**More info**: 
https://twitter.com/enovella_/status/1074101448537985026
https://pbs.twimg.com/media/DugxvdVW4AMk0Iz.jpg
https://pbs.twimg.com/media/Dugvth_XcAASSAz.jpg

**Comment by fs0c131y** [comment]
<off-topic>Someone need to do a full write up on this packer</off-topic>

**Comment by enovella** [comment]
found another sample @ https://koodous.com/apks/54bbf69e6f5529b548526857f5595d7015fc72802cddad3b74ee3a21bb064dca

Probably an older version

**Comment by iGio90** [comment]
You'll find more samples in the Asian side of world. It's not hard to reach the vendor

**Comment by enovella** [comment]
More samples: https://koodous.com/apks/9d46bbb2321bdf738e65e2b7af17ea4bc43bfef6e844c36f2120cfb85a4ca541

**Comment by enovella** [comment]
I believe that this packer must be `Crackproof` (Android SO version). However, I could be maybe wrong. @P0r0 Do you remember something from your research?

This obfuscator has several flavours:
1. Android DEX.(Java) https://www.hypertech.co.jp/en/products/crack-proof-for-android
2. Android SO. (Native)https://www.hypertech.co.jp/en/products/crackproof-for-android-so
3. Unity Android (Gaming) https://www.hypertech.co.jp/en/products/cp-unity-android

**Comment by enovella** [comment]
Another video-game https://koodous.com/apks/b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608

**Comment by enovella** [comment]
Another video-game https://koodous.com/apks/b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608

```java
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608.apk!classes.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, network operator name check, possible vm check
 |-> compiler : dx
[*] b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608.apk!lib/armeabi/lib__57d5__.so
 |-> packer : Nutspacker (Chinese)
[*] b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608.apk!lib/armeabi-v7a/lib__57d5__.so
 |-> packer : Nutspacker (Chinese)
[*] b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608.apk
```

**Comment by enovella** [comment]
More video-games samples @ https://koodous.com/rulesets/5244/apks. Will push the rule as soon as I have some free time.

**Comment by enovella** [comment]
- https://koodous.com/apks/a1a07c14fef1e9176cd89865140e8874bcf244003bee59f419a2af539a93a712
- https://koodous.com/apks/ee4c48fad9cde9e4806432b739004644971d6f82f59e43fd33a4554a17a1b2fb
- https://koodous.com/apks/b4dd87422eb1003c6409b408e6b06bde6aae11da15a10b70a6ab5505becf3608

**Comment by enovella** [comment]
Yeah Unity library has been found to be packed too. [Diaphora](https://github.com/joxeankoret/diaphora) helped me to auto-rename all my previous manual RE work done.

![unity-packed](https://user-images.githubusercontent.com/14809754/52708228-f0e3d980-2f89-11e9-8d7d-ce967382bde7.png)

**Comment by enovella** [comment]
Another clear example with all the native libraries packed:
```sh
[02:19 edu@l0v3 crackproof] >  apkid 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4 
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!classes.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, SIM operator check, network operator name check
 |-> compiler : dx
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libAVProLocal.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libopus.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libAudio360.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libencoder.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libmain.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libAudio360-JNI.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libil2cpp.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libopusJNI.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libFirebaseCppMessaging.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/libFirebaseCppApp-5.2.1.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4!lib/armeabi-v7a/lib__6dba__.so
 |-> packer : CrackProof
[*] 312243d9133ced054a850fa933d1f62adb717a232b79469ab2f58be77c9377a4
[02:19 edu@snps 1] >  

```

**Comment by strazzere** [comment]
Are the rules for `crackproof` submitted anywhere yet for review?

**Comment by enovella** [comment]
Done!

**Comment by strazzere** [comment]
```
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] ./com.square_enix.android_googleplay.khuxww.apk!classes.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, network operator name check, possible VM check
 |-> compiler : dx
 |-> obfuscator : unreadable field names, unreadable method names
[*] ./com.square_enix.android_googleplay.khuxww.apk!lib/armeabi/lib__57d5__.so
 |-> packer : CrackProof
[*] ./com.square_enix.android_googleplay.khuxww.apk!lib/armeabi-v7a/lib__57d5__.so
 |-> packer : CrackProof
[*] ./jp.co.cygames.princessconnectredive.apk!classes.dex
 |-> anti_vm : Build.BOARD check, Build.BRAND check, Build.DEVICE check, Build.FINGERPRINT check, Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, SIM operator check, device ID check, emulator file check, network operator name check, possible Build.SERIAL check, possible VM check, ro.kernel.qemu check, ro.product.device check, subscriber ID check
 |-> compiler : dx
[*] ./jp.co.cygames.princessconnectredive.apk!lib/armeabi-v7a/libcri_mana_vpx.so
 |-> packer : CrackProof
[*] ./jp.co.cygames.princessconnectredive.apk!lib/armeabi-v7a/libil2cpp.so
 |-> packer : CrackProof
[*] ./com.square_enix.android_googleplay.StarOceann.apk!classes.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check
 |-> compiler : dx
[*] ./com.square_enix.android_googleplay.StarOceann.apk!lib/armeabi-v7a/lib__57d5__.so
 |-> packer : CrackProof
```

Rule pushed

**Comment by neobenedict** [comment]
@enovella Did you ever manage to crack the encryption of crackproof?

**Comment by iGio90** [comment]
I did

**Comment by apkunpacker** [comment]
@iGio90 how you did sir , where is your blog regarding unpacking crackproof ?

**Comment by neobenedict** [comment]
@iGio90 Do you have any public information on this? If not, could you recommend what applications I should look into to crack this myself aside from IDA? The first stage of unpacking is fairly simple, but keeping track of everything after the program jumps into the unpacked code was what prevents me going further at the moment.

**Comment by strazzere** [comment]
Folks - let's use the issues in APKiD to talk about exactly that, APKiD.

Please move discussions about unpacking somewhere else. We do _NOT_ condone cracking or piracy. Please stop asking for help in the issue sections of APKiD.

**Comment by iGio90** [comment]
In my blog is the one with "cracking the uncrackable a" as they claim themselves to be uncrackable xD
