### ISSUE TITLE
No info for Fish Island 2

### ISSUE THREAD

**Issue by ter-boom** [rednaga/APKiD#140]
APKiD can not give any info about "com.nhnpixelcube.fishislandII" apk

Nothing except its compiler name:
|-> compiler : dexlib 2.x

**Comment by enovella** [comment]
Hi @ter-boom,

Do you know something about this game? Is it obfuscated? Packed?

BR

**Comment by enovella** [comment]
Definitely its obfuscated. Found a couple of samples with different obfuscation (or configuration)

```
80ac3e9d3b36613fa82085cf0f5d03b58ce20b72ba29e07f7c744df476aa9a92  com.nhnpixelcube.fishislandII_2019-01-09.apk
e1ac17465a101e07d72196d1e25a0e58dd2b952227ee9548b52c2e8cc26bf63e  com.nhnpixelcube.fishislandII.apk
```

### Java obfuscation:
```java
public class IiiIlI1jliiIII1liIll1 {
    public IiiIlI1jliiIII1liIll1() {
        super();
    }

    public String iI1IiIjI1ljlli1IljiiI() {
        int v0 = D.IIj() ^ VV.lil;
        return new String(new char[]{((char)(209427390 ^ v0)), ((char)(209427409 ^ v0)), ((char)(209427413 ^ v0))});
    }
}
```
```java
import android.support.v4.soft.D;
import android.support.v4.soft.VV;

public class ijlijliI11jiI11 {
    public ijlijliI11jiI11() {
        super();
    }

    public String iIjj1ij111iIlIIIijj() {
        int v0 = D.j1I() ^ VV.Ill;
        return new String(new char[]{((char)(0x5F48FA3A ^ v0)), ((char)(0x5F48FA68 ^ v0)), ((char)(0x5F48FA7D ^ v0)), ((char)(0x5F48FA6A ^ v0)), ((char)(0x5F48FA7E ^ v0)), ((char)(0x5F48FA6C ^ v0)), ((char)(0x5F48FA7D ^ v0)), ((char)(0x5F48FA6B ^ v0)), ((char)(0x5F48FA6C ^ v0)), ((char)(0x5F48FA2A ^ v0)), ((char)(0x5F48FA3A ^ v0))});
    }
}
```
I would say that this could be obfuscated with Allatori and some packing is going on.

![screenshot from 2019-02-02 20-27-24](https://user-images.githubusercontent.com/14809754/52168981-289c8700-2729-11e9-8457-9b02283b1433.png)

![screenshot from 2019-02-02 20-31-21](https://user-images.githubusercontent.com/14809754/52169016-b0829100-2729-11e9-80d2-18b5606a57b8.png)

**Comment by enovella** [comment]
Wow there are so many native code to reverse. I saw a lot of `dlopen`, `mprotect` and so many others. Strings obfuscation and encrypted ARM code.

Do you know the name of the protector? Have you tried Simplify on the important classes of the APK? Remember that APKiD does identification only. :)

**Comment by ter-boom** [comment]
I've found it interesting too.
Have no name of the protector =)

**Comment by enovella** [comment]
Feel free to DM me to write a Yara rule for it. Any idea on how to call this protector?

**Comment by enovella** [comment]
@pr3wtd do you think that this obfuscation could be Allatori?

**Comment by enovella** [comment]
Found more samples @ https://koodous.com/rulesets/5249/apks

**Comment by enovella** [comment]
The protector could be this:

**Comment by enovella** [comment]
The protector could be this: 

- https://www.toast.com/service/security/appguard

**Comment by enovella** [comment]
The protector and/or packer could be this: 

- https://www.toast.com/service/security/appguard

Features:
- Detect execution of cheating tools
- Detect execution of rooting or jailbreaking
- Detect code fabrication
- Detect debugging of protected apps
- Detect fabrication of signature or modules
- Detect emulation
- Detect speed hack
- Encrypt DEX Files
- Encrypt game execution files (Unit3D, Cocos2d-x)

**Comment by enovella** [comment]
However, there is another brand calling their solution `AppGuard` (us). This new one seems to be Chinese, Japanese or Korean.

**Comment by enovella** [comment]
Done!

```
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] com.nhnpixelcube.fishislandII_2019-01-09.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] com.nhnpixelcube.fishislandII_2019-01-09.apk
 |-> packer : AppGuard (TOAST-NHNent)
[*] com.nhnpixelcube.fishislandII.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] com.nhnpixelcube.fishislandII.apk
 |-> packer : AppGuard (TOAST-NHNent)
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] new/9604078ae01d8b737ef26b75119cbaff09e3dea88e3a6b2b9b909dd0dfcdee23!classes.dex
 |-> compiler : dexlib 2.x
[*] new/9604078ae01d8b737ef26b75119cbaff09e3dea88e3a6b2b9b909dd0dfcdee23
 |-> packer : AppGuard (TOAST-NHNent)
[*] new/f8691d71c7a0189515a8554112a507cf9657f54125d3c7b220ffdd283a5577b1!classes.dex
 |-> compiler : dexlib 2.x
[*] new/f8691d71c7a0189515a8554112a507cf9657f54125d3c7b220ffdd283a5577b1
 |-> packer : AppGuard (TOAST-NHNent)

```

**Comment by strazzere** [comment]
@enovella Can you submit the rule you've created for this one? A clean pull/build from `HEAD` right now results in no detections;

```
apkid .
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] ./com.dnt7.threeW.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] ./com.nhnent.SKRWBY.apk!classes.dex
 |-> compiler : dexlib 2.x
```

**Comment by enovella** [comment]
Done!

**Comment by strazzere** [comment]
Confirmed done via https://github.com/rednaga/APKiD/issues/184;
```apkid toast     
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] toast/com.dnt7.threeW.apk
 |-> packer : AppGuard (TOAST-NHNent)
[*] toast/com.dnt7.threeW.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] toast/com.nhnent.SKRWBY.apk
 |-> packer : AppGuard (TOAST-NHNent)
[*] toast/com.nhnent.SKRWBY.apk!classes.dex
 |-> compiler : dexlib 2.x
```
