### ISSUE TITLE
[BUG]different results using apkid.scan and apkid.scan_apk

### ISSUE THREAD

**Issue by superpoussin22** [rednaga/APKiD#141]
If I analyse an apk using apkid.scan_apk only results from dex files are reported
if I use apkid.scan with a directory which contain the apk then obfuscator like Dexprotector is displayed and also result from Dex files.

So apkid.scan provide more accurate results 

Why ?

**Comment by enovella** [comment]
Not sure I got you well but some rules are only applicable to the content of APK files. These never won't match for `dex` or `so` files. In any case, it'd be appreciated if you could provide more information.

**Comment by superpoussin22** [comment]
with apkid.scan_apk:
{"/root/.MobSF/uploads/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx.apk!classes.dex": {"compiler": ["dx"], "anti_vm": ["Build.FINGERPRINT check"]}, "/root/.MobSF/uploads/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx.apk!classes2.dex": {"compiler": ["dx"]}}

with apkid.scan (and apk in the directory):
{"/root/.MobSF/uploads/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx.apk": {"packer": ["DexProtector"]}, "/root/.MobSF/uploads/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx.apk!classes.dex": {"compiler": ["dx"], "anti_vm": ["Build.FINGERPRINT check"]}, "/root/.MobSF/uploads/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx.apk!classes2.dex": {"compiler": ["dx"]}}

**Comment by enovella** [comment]
Highlight the code please :)

**Comment by CalebFenton** [comment]
Are you asking why different APIs do different things? I'm not sure how to answer this. What's the question?

It's been a while, but it looks like `scan_apk` scans the contents of the apk while `scan` scans the container (the zip file) as well. Feel free to re-open if you have a suggestion.
