### ISSUE TITLE
[Question]Updated rules in PyPi package

### ISSUE THREAD

**Issue by superpoussin22** [rednaga/APKiD#142]
Hello,

Python pip package for APKiD contains old version of rules.

Did you plan to update the package on a regular basis ? (If yes How often ?)

an update plan would be great 

Thanks in advance

**Comment by enovella** [comment]
I think that never used the `Pypi` install, but could you please provide examples of installation and rules counting? Why and where do you think that the issue is?

**Comment by superpoussin22** [comment]
did not say this is an issue simply that if someone use the PyPi package the rules are from the date of the package build time, so if the pypi package is updated only when there's a new apkid version, people won't have the last rules dictionnary.

I was thinking of an enhancement :)

**Comment by strazzere** [comment]
Done - will need to figure out a way to automate this in the future...

https://pypi.org/project/apkid/2.1.0/
