### ISSUE TITLE
Determine if "md5" obfuscator is actually just Mono

### ISSUE THREAD

**Issue by CalebFenton** [rednaga/APKiD#149]
It's possible that this isn't a real obfuscator but is just Mono libraries.

Original comment from @enovella in https://github.com/rednaga/APKiD/issues/105#issuecomment-476898282

@enovella, can you share relevant sample hashes? The comment you posted only contains a partial hash of a file.

**Comment by enovella** [comment]
https://github.com/rednaga/APKiD/issues/105#issue-341955448

**Comment by CalebFenton** [comment]
@enovella I should have been more clear. It's not possible to generalize or plot a trend from a single data point, and that's all that particular comment has. The "possible related hashes" are from the black magic of VT similarity and none of them have been confirmed using any other mechanism.

**Comment by enovella** [comment]
p0x [9:12 AM]
@caleb @enovella I don't know if this might help

```Beginning with Xamarin.Android 5.1, the type name of an activity is based on the MD5SUM of the assembly-qualified name of the type being exported. This allows the same fully-qualified name to be provided from two different assemblies and not get a packaging error. (Before Xamarin.Android 5.1, the default type name of the activity was created from the lowercased namespace and the class name.)```

**Comment by enovella** [comment]
Whenever you got some time, please remove this rule @CalebFenton

**Comment by CalebFenton** [comment]
Thanks for checking on this @enovella 👍
