### ISSUE TITLE
Error using prep_release

### ISSUE THREAD

**Issue by superpoussin22** [rednaga/APKiD#152]
hello
since you'r last merge there's a few error

Traceback (most recent call last):
  File "prep-release.py", line 33, in <module>
    from apkid.output import colorize_tag
  File "/yara-python/APKiD/apkid/__init__.py", line 36, in <module>
    from apkid.apkid import Scanner, Options
  File "/yara-python/APKiD/apkid/apkid.py", line 32, in <module>
    from .output import OutputFormatter
  File "/yara-python/APKiD/apkid/output.py", line 33, in <module>
    from .rules import RulesManager
  File "/yara-python/APKiD/apkid/rules.py", line 33, in <module>
    class RulesManager(object):
  File "/yara-python/APKiD/apkid/rules.py", line 42, in RulesManager
    def load(self) -> yara.Rules:
AttributeError: module 'yara' has no attribute 'Rules'

**Comment by CalebFenton** [comment]
I think you need to update yara python. Could you try that?

If that doesn't work, please include the output of `pip freeze `

**Comment by superpoussin22** [comment]
pip freeze result :

pypandoc==1.4
yara-python==3.7.0.999

**Comment by superpoussin22** [comment]
the error occurs also using the dockerfile on the git

**Comment by CalebFenton** [comment]
Thanks for reporting this error.  The problem was my environment wasn't completely clean and I didn't test everything enough. I think everything should be fixed now, but the installation instructions have changed.

It looks like the latest official yara python is completely compatible with APKiD with just a simple build option. Hurray! So try following the readme instructions after `pip uninstall yara-python`, and try the Docker too.

**Comment by superpoussin22** [comment]
@CalebFenton  Dockerfiel is Ok , well done 

using pip install apkid , I have :

Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 6, in <module>
    from apkid import main
ModuleNotFoundError: No module named 'apkid'

**Comment by CalebFenton** [comment]
The `find_packages` function called in `setup.py` which decides which files to include must have changed how it works. If you tell it to include package "apkid" what it does is _not_ include package "apkid", so 🤷‍♂. It's fixed now.

Try `pip install --upgrade apkid` to get 2.0.1.

**Comment by CalebFenton** [comment]
Somehow your comment happens in the future. Congratulations for inventing time travel.

<img width="577" alt="Screen Shot 2019-05-08 at 7 38 04 AM" src="https://user-images.githubusercontent.com/1356658/57383781-42080180-7164-11e9-8ac5-c0d0c461d948.png">

**Comment by superpoussin22** [comment]
@CalebFenton : apkid is working fine now :)

BTW, did you change something in the way of calling apkid with python ?

I try 

   from apkid import apkid
    from apkid import __version__ as apkid_ver
    logger.info("Running APKiD %s on: %s", apkid_ver,
                file_name)
    result = apkid.scan(dest_dir, 30, True, dest_dir, True)

and I have: 
 module 'apkid.apkid' has no attribute 'scan'

**Comment by CalebFenton** [comment]
Glad it's working.

Yeah, the api changed a bit as it was rewritten. It should be a bit cleaner
now. Try it out.

**Comment by superpoussin22** [comment]
thanks @CalebFenton
