### ISSUE TITLE
Latest install instructions

### ISSUE THREAD

**Issue by ajinabraham** [rednaga/APKiD#157]
This PR looks merged: https://github.com/VirusTotal/yara/pull/1073
The install instructions need an update?

**Comment by CalebFenton** [comment]
It also needs to be updated in yara-python. So waiting in them up update
the yara submodule.

**Comment by strazzere** [comment]
Closing since the instructions are fine for the time being, just did an install myself on a fresh ubuntu 18.04 machine.

**Comment by superpoussin22** [comment]
@CalebFenton yara 3.11.0 is out
