### ISSUE TITLE
APKiD doesn't work inside virtualenv

### ISSUE THREAD

**Issue by ajinabraham** [rednaga/APKiD#173]
```
python3 -m venv venv
source venv/bin/activate
pip install --upgrade wheel
pip wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.11.0
pip install --no-index --find-links=/tmp/yara-python yara-python
pip install apkid
```

```
$ apkid  abc.apk -j
Traceback (most recent call last):
  File "/Users/Box/Code/apkid/venv/bin/apkid", line 11, in <module>
    sys.exit(main())
  File "/Users/Box/Code/apkid/venv/lib/python3.6/site-packages/apkid/main.py", line 60, in main
    scanner.scan(input)
  File "/Users/Box/Code/apkid/venv/lib/python3.6/site-packages/apkid/apkid.py", line 103, in scan
    results = self.scan_file(path)
  File "/Users/Box/Code/apkid/venv/lib/python3.6/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
```

works fine without venv

**Comment by strazzere** [comment]
Uninstall it from your non-virtualenv and recreate the virtualenv explicitly stating to not use site packages.

Other than that - I'm not sure what to tell you. I suggest you diving into this and documenting what is wrong - but if it works outside of virtualenv, in docker, etc -- then it seems like it's local to something you're doing with virtualenv -- no?

**Comment by ajinabraham** [comment]
I tried debugging but looks like the exception is coming from C.
```
ipdb> n
> /x/venv/lib/python3.6/site-packages/apkid/apkid.py(119)scan_file()
    118                 return results
--> 119             f.seek(0)
    120             matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)

ipdb> n
> /x/venv/lib/python3.6/site-packages/apkid/apkid.py(120)scan_file()
    119             f.seek(0)
--> 120             matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
    121             if len(matches) > 0:

ipdb> s
yara.Error: internal error: 34
> /x/venv/lib/python3.6/site-packages/apkid/apkid.py(120)scan_file()
    119             f.seek(0)
--> 120             matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
    121             if len(matches) > 0:
```

```
> /x/venv/lib/python3.6/site-packages/apkid/apkid.py(119)scan_file()
    118                 return results
--> 119             f.seek(0)
    120             matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
ipdb>  self.rules.match(data=f.read())
*** yara.Error: internal error: 34
```

**Comment by CalebFenton** [comment]
What @strazzere could work. It looks like you have two yara-python modules installed and apkid is using the wrong one. FWIW, I excluslively use Python with virtualenv so I know it works.

If I look at my own import paths, I have several non-venv paths that come before the venv path:

```
$ python
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/yara_python-3.10.0-py3.7-macosx-10.14-x86_64.egg', '/Users/caleb/repos/apkid']
```

This would imply that you should test by installing yara-python outside of venv. If it's not installed or you want to have two versions, try modifying your sys path.

**Comment by ajinabraham** [comment]
Quick update: It works if I create the venv with `--system-site-packages`

**Comment by strazzere** [comment]
Right, the exception is coming from yara because the dex module is not present.

Using `--system-site-packages` sort of defies why you would want to use a virtualenv. But if that works for you, have at it.

However, this indicates that you're not actually installing the proper yara-python version in your virtualenv, which is why it was giving you errors.

Just going to close this since it isn't a bug in apkid.

**Comment by ajinabraham** [comment]
I just followed the exact instructions here: https://github.com/rednaga/APKiD#installing

**Comment by strazzere** [comment]
I understand...

But those directions worked for you, me and @CalebFenton.

Then you've installed it in your virtual environment and it failed. (This is not what is described in the directions).

Then you used `--system-site-packages` which means you've used the `yara-python` you installed outside of the virtual-environment which is from the instructions.

So the instructions worked fine, see?

**Comment by ajinabraham** [comment]
Yes thats correct, But I wanted to use it inside virtualenv without `--system-site-packages` and also curious about why it was failing inside venv.

**Comment by strazzere** [comment]
So, like I've already said, something is wrong with how you specifically are installing/using the virtual environment. Maybe it doesn't like / or pick up the actual c code.

Again, this seems like a virtualenv issue, not an apkid one. Especially since @CalebFenton and myself are both running it inside a virtual environment without issues.

I suggest nuking everything inside and out of you're virtualenv, trying again, figuring out what is/isn't compiling and asking on a virtualenv support thread for help. You're not likely to get that help here.

**Comment by ajinabraham** [comment]
APKiD used to work for me in virtualenv as well. But recently it stopped working.
Since you guys are saying it's working in virtualenv for you, I just created a docker container to isolate the problem.

Dockerfile
```
FROM python:3-slim
RUN apt-get update -qq && \
    apt-get install -y git build-essential

WORKDIR /app
RUN python3 -m venv venv
RUN . /app/venv/bin/activate && \
    pip install --upgrade wheel && \
    pip wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.11.0 && \
    pip install --no-index --find-links=/tmp/yara-python yara-python && \
    pip install apkid
COPY abc.apk .
CMD ["bash", "-c", ". /app/venv/bin/activate && apkid /app/abc.apk -j"]
```

```
$ docker build -t apkid .
Sending build context to Docker daemon  3.466MB
Step 1/7 : FROM python:3-slim
 ---> 6b52e13b1d32
Step 2/7 : RUN apt-get update -qq &&     apt-get install -y git build-essential
 ---> Using cache
 ---> c47aa4c61ee8
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> 83e43f0e5e43
Step 4/7 : RUN python3 -m venv venv
 ---> Using cache
 ---> eb5c9b447074
Step 5/7 : RUN . /app/venv/bin/activate &&     pip install --upgrade wheel &&     pip wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.11.0 &&     pip install --no-index --find-links=/tmp/yara-python yara-python &&     pip install apkid
 ---> Using cache
 ---> eb167798f7d5
Step 6/7 : COPY abc.apk .
 ---> Using cache
 ---> b6cf438ca849
Step 7/7 : CMD ["bash", "-c", ". /app/venv/bin/activate && apkid /app/abc.apk -j"]
 ---> Running in db3697000f06
Removing intermediate container db3697000f06
 ---> 92fdeb04a712
Successfully built 92fdeb04a712
Successfully tagged apkid:latest

$ docker run -it apkid
Traceback (most recent call last):
  File "/app/venv/bin/apkid", line 10, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.8/site-packages/apkid/main.py", line 60, in main
    scanner.scan(input)
  File "/app/venv/lib/python3.8/site-packages/apkid/apkid.py", line 103, in scan
    results = self.scan_file(path)
  File "/app/venv/lib/python3.8/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
```

So it is clearly not working inside virtualenv or your virtualenv is setup differently.

Probably a virtualenv issue, but the error message from yara's C lib is not helping much to identify the issue.

**Comment by strazzere** [comment]
Per my previous comment;
`Right, the exception is coming from yara because the dex module is not present.`

That is what internal error 34 means.

Somehow your virtual environment isn't compiling with the flags you've passed to it.

**Comment by ajinabraham** [comment]
@strazzere  I think the dex module exception is because apkid is not updated in PyPI.
APKiD in PyPI is pinned to `yara-python==3.10.0`. This will uninstall the dex enabled yara-python 3.11.0 when you try to install apkid as per the instructions given in the readme.

``
$ pip install apkid
Collecting apkid
  Using cached https://files.pythonhosted.org/packages/ac/85/1bca460c38af3183db7d20252c49bb58c3cb8c5de179c17246317599e14d/apkid-2.0.3-py2.py3-none-any.whl
Processing /x/Library/Caches/pip/wheels/d7/f4/54/167bd160e04e10ba03629222d5b0447e7571eba690e75d189e/yara_python-3.10.0-cp37-cp37m-macosx_10_9_x86_64.whl
Requirement already satisfied: argparse in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from apkid) (1.4.0)
Installing collected packages: yara-python, apkid
  Found existing installation: yara-python 3.11.0
    Uninstalling yara-python-3.11.0:
      Successfully uninstalled yara-python-3.11.0
Successfully installed apkid-2.0.3 yara-python-3.10.0
```

So you should update the package in PyPI or change the install instruction to

``
pip wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.10.0
```
