### ISSUE TITLE
Install errors traceback

### ISSUE THREAD

**Issue by thecjin** [rednaga/APKiD#174]
Hello, what is the fix for this? Have python 3.7 installed.
Get this error when running apkid

[+] APKiD 2.0.3 :: from RedNaga :: rednaga.io
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/apkid/main.py", line 56, in main
    rules = options.rules_manager.load()
  File "/usr/local/lib/python3.7/dist-packages/apkid/rules.py", line 43, in load
    self.rules = yara.load(self.rules_path)
yara.Error: rules file "/usr/local/lib/python3.7/dist-packages/apkid/rules/rules.yarc" is incompatible with this version of YARA

**Comment by strazzere** [comment]
Sounds like you haven't installed the correct version of yara per the error message.

I would suggest you use the docker version to ensure your environment is in the correct state. Otherwise, refollow the steps for installing and list what you've done - not sure the error message.
