### ISSUE TITLE
i got nothing after run apkid

### ISSUE THREAD

**Issue by rexi1r** [rednaga/APKiD#182]
@cdchen @reox @strazzere @iantruslove @CalebFenton 
environment:
Ubuntu 18.04.3 LTS
python3 version: Python 3.6.9
apkid : [+] APKiD 2.0.3 :: from RedNaga :: rednaga.io
yara-python-3.11.0

after the run command: apkid -j -o ./Test.zip
if got nothing .just command execute and finish without any result.

what can i do? what is wrong with this?

**Comment by strazzere** [comment]
You'll need to provide the APK you're scanning, what you're expecting the results to be and why this is considered a bug/failure case.

Otherwise, we literally can't do anything to try and help.

**Comment by strazzere** [comment]
Closing -- feel free to reopen with a hash (which is obtainable) or attaching the apk in question.
