### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#183]
Hi i am getting error

" error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/ "

its requires GB's of space and internet and either i can not find simple build tools in small size
Please give me a way to install apkid without this Microsoft Visual Studio build tools

**Comment by strazzere** [comment]
> Please give me a way to install apkid without this Microsoft Visual Studio build tools.

Use the docker container that is provided.
