### ISSUE TITLE
Add Rule For This ApkProtector

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#184]
[myapp.apk.zip](https://github.com/rednaga/APKiD/files/3995025/myapp.apk.zip)

please rename this sample to myapp.apk , its packed by ApkProtector available on play store

https://play.google.com/store/apps/details?id=com.mcal.dexprotect

i don't know what APKID give output because i am unable to install it but i am sure its something new packer which is available on play store
I can provide Packer itself if you guys need more packed sample so with packer you can pack any apk and test.
Thanks

**Comment by enovella** [comment]
Hi @apkunpacker,

can you provide us more samples? If so and you can arbitrary obfuscate APKs, could you provide us both unobfuscated and obfuscated?

Thanks for opening the issue.

**Comment by enovella** [comment]
Is this Russian malware?
![Screenshot from 2019-12-23 14-28-30](https://user-images.githubusercontent.com/14809754/71360564-972c4280-2590-11ea-942c-b265b4e5d6d5.png)

![Screenshot from 2019-12-23 14-31-22](https://user-images.githubusercontent.com/14809754/71360702-f4c08f00-2590-11ea-9217-6d540d831942.png)

**Comment by apkunpacker** [comment]
[apkpacker.apk.zip](https://github.com/rednaga/APKiD/files/3995320/apkpacker.apk.zip)

Hi @enovella sir , Please rename to apkpacker.apk , it is packer itself so you can try and pack yourself any apk sample  with packer and this packer is packed with own packer

**Comment by enovella** [comment]
Here you go....

```sh
[18:49 edu@xps apkprotector] >  apkid .
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] ./apkpacker.apk!assets/ba/nc.mz
 |-> compiler : dx
[*] ./apkpacker.apk!assets/ba/nd.mz
 |-> compiler : dx
[*] ./apkpacker.apk!assets/ba/ne.mz
 |-> compiler : dx
[*] ./apkpacker.apk!assets/ba/nf.mz
 |-> compiler : dx
[*] ./apkpacker.apk!classes.dex
 |-> compiler : dx
[*] ./myapp.apk!classes.dex
 |-> compiler : dx
```

**Comment by enovella** [comment]
Wrote a rule for it and I will be sharing it soon with you.

**Comment by apkunpacker** [comment]
[sample.apk.zip](https://github.com/rednaga/APKiD/files/3996953/sample.apk.zip)
Thanks
By The Way One More Sample To Test. Regards

**Comment by romainthomas** [comment]
> Is this Russian malware?
I unpacked the application and it does not seem to be a malware

**Comment by enovella** [comment]
Do we know if this packer is a new version of this one?  @strazzere 

```sh
rule apkprotect : packer
{
  meta:
    description = "APKProtect"

  strings:
    $key = "apkprotect.com/key.dat"
    $dir = "apkprotect.com/"
    $lib = "libAPKProtect.so"

  condition:
    is_apk and ($key or $dir or $lib)
}
```

**Comment by strazzere** [comment]
I don't believe anyone has looked into this one -- if they have, then they haven't added the details here...

**Comment by apkunpacker** [comment]
> Do we know if this packer is a new version of this one? @strazzere
> 
> ```shell
> rule apkprotect : packer
> {
>   meta:
>     description = "APKProtect"
> 
>   strings:
>     $key = "apkprotect.com/key.dat"
>     $dir = "apkprotect.com/"
>     $lib = "libAPKProtect.so"
> 
>   condition:
>     is_apk and ($key or $dir or $lib)
> }
> ```

I don't think so , this packer is a fork of a free packer available on play store 

https://play.google.com/store/apps/details?id=mph.trunksku.apps.dexpro
Thats free one and pack the dex also , REQUEST TO ADD RULE FOR THIS PACKER ALSO . 
Should i open a new issue for this packer ?
If you need source , i have source of this packer also . ask anytime if you need

**Comment by enovella** [comment]
Please open a new ticket with all the info, samples and URLs.
