### ISSUE TITLE
AppSolid

### ISSUE THREAD

**Issue by circleous** [rednaga/APKiD#19]
Made by Medusah author, AppSolid somewhat have same behaviour with Medusah. Like how it loads encrypted dex. Lately, in some latest version they added string obfuscator. This is the structure of apk (snipped)
```
lib
└── armeabi-v7a
    ├── lib1c6895cddfbfe7b5b7984726fa93806d1.so (loader)
    ├── ...
    ├── libf63855cbd2a6b3dd91be48eee86498421.so (unity loader)
    └── ...
```
```
assets
├── bin
├── common
├── high_resolution.png (encrypted dex)
└── Shader
``` 
Dexcalls path somewhat doesnt really change, .../.0395f312/.88c166a1/.63d49db7/.cfc9fa24/.406dd60f/android_support.jar. 
What make this unique is loader lib name isnt static, i mean filename are changed in every apk.

Some reference:
[1] https://appsolid.co/
[2] https://medium.com/@seworks/introducing-appsolid-for-unity-33c711f16f02#.ov3quusls

Samples:
[1] [5c1f14c1674c6f3ff72d9a017b083023d6c59635bec83718afec2d23372f84f4](https://koodous.com/apks/5c1f14c1674c6f3ff72d9a017b083023d6c59635bec83718afec2d23372f84f4/) 
[2] [2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344](https://koodous.com/apks/2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344/)

**Comment by circleous** [comment]
This is just my guessing game. Judging by Medusah isnt updated for a long time and this packer almost has same behaviour like Medusah. This might be newer version of Medusah or its really new product from seworks (AppSolid). Need some thought for it.

**Comment by CalebFenton** [comment]
Thanks for the well-written info (and a PR, nice)!

There seems to be a pretty strong relationship between the two judging by some of the package names / strings here: https://www.pnfsoftware.com/blog/2016/06/

My guess is AppSolid is an attempt to productize the earlier Medusah version. I think it'd be good if we could indicate that the two packers are related. This could be either as a comment in the rules or by simply naming this new packer medusah_appsolid. I also think it'd be good to rename Medusa -> Medusah. What do you think?

**Comment by circleous** [comment]
I think Medusa should be renamed to Medusah. Since both have different meaning. I'd rather go with medusah_appsolid since some peeps dont bother to take a look at source and giving some comments into it.

**Comment by CalebFenton** [comment]
I agree with your reasoning. 👍

**Comment by CalebFenton** [comment]
Thanks for raising the issue and submitting code. I slightly tweaked your PR here https://github.com/rednaga/APKiD/commit/806e29b026e71f141ebb71873f56252a6d5b644b

The reason is so that the rules distinguish between the different variants but still group them in the same family. A good example are the dexlib rules that try and distinguish between three different versions (1.x, 2.x beta, and 2.x).

**Comment by enovella** [comment]
Hi,

Why are we printing twice the packer? Shouldn't be triggered at dex level instead of apk & dex level? 
It can be a bit of redundancy.

```
> apkid  2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] 2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344
 |-> packer : Medusah (AppSolid)
[*] 2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344!classes.dex
 |-> anti_vm : possible vm check
 |-> compiler : dexlib 2.x
 |-> packer : Medusah (AppSolid)
[*] 2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344!lib/armeabi-v7a/libunity.so
 |-> anti_root : Root detectors, Superuser
[*] 2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344!lib/armeabi-v7a/libcc033cb351bc4c749e293a81fde1bc621.so
 |-> obfuscator : Obfuscator-LLVM version 3.6.1
[*] 2870eb73c4e54d436e465fd478de610ebdca45485ac3abcf5c0396e878ebb344!lib/armeabi-v7a/lib44689a6d1ab720ca1b3198e16310f67e1.so
 |-> obfuscator : Obfuscator-LLVM version 3.6.1
```
