### ISSUE TITLE
[New Packer] Add Rule To For Dexprotector

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#195]
This Is The Free Packer Packer Available On Play Store With Name :- Dexprotector for Aide
Link: 
https://play.google.com/store/apps/details?id=mph.trunksku.apps.dexpro

Sample : With Above Apk Link Many Sample Can be Created.

APKID Output: Not Available because i am unable to run it on my machine. So attached output of GDA decompiler by charles2gan
![dp](https://user-images.githubusercontent.com/27184655/71461482-f5963280-27d5-11ea-8640-35bb8be20dd0.JPG)

Source of Packer : Old Version source but enough to explain its working 

[DexProtector for AIDE IDE_v3.0 Source.zip](https://github.com/rednaga/APKiD/files/4001584/DexProtector.for.AIDE.IDE_v3.0.Source.zip)

**Comment by enovella** [comment]
Do you have more samples?

**Comment by apkunpacker** [comment]
with above apk you can pack any apk to make it new saple

**Comment by apkunpacker** [comment]
with above apk you can pack any apk to make it new sample

**Comment by enovella** [comment]
Would you like to create some? I can create the rule for it.

**Comment by CalebFenton** [comment]
We will generally prioritze issues with samples in the wild. This app only has 500 installs and I can't fathom why a developer would use a mobile app to protect their apks.

**Comment by apkunpacker** [comment]
@CalebFenton sir you are right but atleast this simple packer keep simple piracy tool like lucky patcher away with just root . Xposed and frida user still can emulate in app purchase and lvl with it . It has low install because its mostly available in ad free version on telegram or on many other site. I wish someone add it in apkid whenever it needs.

**Comment by enovella** [comment]
@apkunpacker these are your samples for this packer, right?

[APK Export.zip](https://github.com/rednaga/APKiD/files/4019857/APK.Export.zip)
[Encrypt Decrypt.zip](https://github.com/rednaga/APKiD/files/4019858/Encrypt.Decrypt.zip)
[Color Picker.zip](https://github.com/rednaga/APKiD/files/4019859/Color.Picker.zip)

**Comment by CalebFenton** [comment]
@apkunpacker can you help me understand why you'd want to detect these? My background is in malware research and I'm curious.

It seems unlikely that you'd encounter APKs like this since the protection happens on the device. The developer would have to build the app normally, install to their device / emulator, protect it with this packer, export it from the device, and distribute it. Seems like a lot of extra work, so I'm guessing I don't understand the use case.

**Comment by enovella** [comment]
Is this malware? https://play.google.com/store/apps/details?id=mph.trunksku.apps.dexpro

**Comment by enovella** [comment]
```sh
[01:33 edu@xps dexprotector-aide] >  apkid .
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] ./APKExport.apk
 |-> packer : DexProtector for AIDE
[*] ./APKExport.apk!classes.dex
 |-> anti_vm : ro.kernel.qemu check
 |-> compiler : dexlib 2.x
[*] ./EncryptDecrypt.apk
 |-> packer : DexProtector for AIDE
[*] ./EncryptDecrypt.apk!classes.dex
 |-> anti_vm : ro.kernel.qemu check
 |-> compiler : dexlib 2.x
[*] ./ColorPicker.apk
 |-> packer : DexProtector for AIDE
[*] ./ColorPicker.apk!classes.dex
 |-> anti_vm : ro.kernel.qemu check
 |-> compiler : dexlib 2.x
```

**Comment by apkunpacker** [comment]
@CalebFenton sir after reading its review on play store i know that any apk protected by this packer always contains 1-2 virus/malware . By the way i didn't scanned the sample but many review aren't fake right ? So i decided to open an issue . @enovella  sir yes they are the sample i sended on telegram.  Packer detected now , nice . Thanks you both of you . Closing this issue

**Comment by enovella** [comment]
Do you know more packers that APKiD doesn't detect yet? Thanks.

**Comment by apkunpacker** [comment]
Would you like to detect obfuscator too? I have some apk obfuscated with stringer 9

**Comment by enovella** [comment]
APKiD detects any kind of Protector, obfuscator, packer, compiler and so on... Please fire a ticket with enough info.

**Comment by apkunpacker** [comment]
@enovella sir i will let you know whenever i get something new
