### ISSUE TITLE
[MISSED] Unknown dexprotect(or) version (?)

### ISSUE THREAD

**Issue by eybisi** [rednaga/APKiD#197]
**Provide the file**
[e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a](https://koodous.com/apks/e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a)

**Describe the detection issue**
Unknown or missed dexprotector version. There is a file inside of apk called `dexpro-build.properties`: 
```
reverse_detection=true
hooks_detection=false
device_detection=false
signature_detection=false
show_toast=true
build.version_name=: 1.5 (Beta)
build.version_code=: 15
build.developer=***
build.company=***
```
APK structure:

![dexpro](https://user-images.githubusercontent.com/21275072/71550184-6b1f2000-29db-11ea-9308-8c85c29aba15.png)

**APKiD current results...**
```
eybisi@abc: apkid e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a   
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a!classes.dex
 |-> compiler : dexlib 2.x
[*] e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a!status404error/duration/checker/BuildConfig.dex
 |-> compiler : dx
[*] e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a!status404error/duration/checker/CheckDuration$Duration.dex
 |-> compiler : dx
[*] e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a!status404error/duration/checker/CheckDuration$DurationListener.dex
 |-> compiler : unknown (please file detection issue!)
[*] e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a!status404error/duration/checker/CheckDuration.dex
 |-> compiler : dx

```

**Comment by apkunpacker** [comment]
i am 99% sure its related to #195

**Comment by CalebFenton** [comment]
@apkunpacker why do you think they're related?

**Comment by enovella** [comment]
@eybisi I cannot get this sample, do you mind uploading it here?

```sh
This site can’t be reachedThe webpage at https://warehouse.koodous.com/download/LHCz0oO+nciS0bTGAIXrBKO3JEdf5ddyQ5SwLG0FMv8iNnvBzLVD3gWsSGeiws6c/H1ut5YkFpt+NQ4espBFGIIoQz5slHOTk9jC079We8m5PggFZNobPBin3iuInKIf6pbSwOZx1hL0CtofsBtrzw== might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

**Comment by enovella** [comment]
[e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a.zip](https://github.com/rednaga/APKiD/files/4021369/e113be26d90fe2cb287009345139fba0c550a67b15c3022eb5dc13aa0eb8235a.zip)

thanks @strazzere

**Comment by enovella** [comment]
> i am 99% sure its related to #195

seems very similar yeah

**Comment by enovella** [comment]
@eybisi can you try to find more samples?

**Comment by enovella** [comment]
Can @eybisi test if it is now detected?
