### ISSUE TITLE
invalid field name "data_offset" when running prep-release.py

### ISSUE THREAD

**Issue by idanr1986** [rednaga/APKiD#2]
Traceback (most recent call last):
  File "prep-release.py", line 25, in <module>
    rules = yara.compile(filepaths=yara_files)
yara.SyntaxError: apkid/rules/dex/obfuscators.yar(64): invalid field name "data_offset"

**Comment by strazzere** [comment]
@idanr1986 did you install our specific version of yara? This contains the dex module, directions are on the README under installing;

```
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid
The yara-python clone and compile steps are temporarily necessary because it installs our DEX Yara module. We're working on removing this step.
```

**Comment by idanr1986** [comment]
yes , I'm working on OS X  the compiled yara.so is in 2.7/lib/python2.7/site-packages

**Comment by CalebFenton** [comment]
Could you try pulling and making yara-python  again? Be sure to update submodule.

That field was renamed from data_off to data_offset.

**Comment by idanr1986** [comment]
ok if you use the commands in the readme file yard-python checkout form your yara fork this checkout 94fc60a1014f88a5f27df7ab694c93eaf0e62cc0 that does not contains the last commit:
'Prefer "offset" over "off"'

**Comment by CalebFenton** [comment]
Ah hah! I see the issue. I thought I had pushed the fix for that but didn't. Sorry!

Try pulling yara-python now, and setup.py should get the latest submodule and it should work.

**Comment by CalebFenton** [comment]
Closing this. Feel free to re-open if that doesn't fix your issue.
