### ISSUE TITLE
invalid field name "header"

### ISSUE THREAD

**Issue by avkiller** [rednaga/APKiD#208]
[*] Compiling Yara files                                                                                
Traceback (most recent call last):                                                                      
  File "\APKiD\prep-release.py", line 49, in <module>                                   
    rules = rules_manager.compile()                                                                     
  File "\APKiD\apkid\rules.py", line 61, in compile                                     
    self.rules = yara.compile(filepaths=yara_files)                                                     
yara.SyntaxError: \APKiD\apkid\rules\dex\abnormal.yara(67): invalid field name "header"

**Comment by strazzere** [comment]
This is not a detection issue, this is a compilation issue.

What version of python are you running, what have you pip installed, what is your yara-python versions, did you read all the instructions in the read me, did this fail in the docker container?

**Comment by avkiller** [comment]
Python 3.7.6
yara-python 3.11.0
windows 10

* install yara
pip install --upgrade wheel
pip wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.11.0
pip install --no-index --find-links=/tmp/yara-python yara-python

* install apkid
git clone https://github.com/rednaga/APKiD
cd APKiD
./prep-release.py

**Comment by strazzere** [comment]
`./prep-release.py` will default to `#!/usr/bin/env python` which may be different than you're expecting?

I'd double back and ensure that both your `pip` and `python` aliases are all pointing to the same versioning.

Though, this is also windows and I have no idea what might be wrong...

@CalebFenton  any ideas?

**Comment by avkiller** [comment]
I don't know if it is related to windows10

old windows7 Seems no problem

don't know if there is a problem upgrade windows 10

**Comment by enovella** [comment]
What about forcing pip to use py3.6 or py3.7?
`pip3.7 wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex"`

The same for compiling rules and setup.py.

If this doesn't solve your issue, how many pips do you got in your box?
```sh
[16:38 edu@xps tmp] >  pip
pip     pip2    pip2.7  pip3    pip3.6  
[16:38 edu@xps tmp] >  pip
pip     pip2    pip2.7  pip3    pip3.6  
[16:38 edu@xps tmp] >  which pip
pip is /usr/local/bin/pip
pip is /usr/bin/pip
```

**Comment by avkiller** [comment]
user python3.7 pip3.6  Same problem

apkid\rules\dex\abnormal.yara(86): invalid field name "header"


I see if I can find a virtual machine for windows7

maybe yara-python bug

**Comment by CalebFenton** [comment]
I'm pretty sure the problem is the yara library that's being loaded doesn't have the dex module. There's a related issue here: https://github.com/rednaga/APKiD/pull/166

While yara might be the root cause, the fix is probably environmental.

Find where your yara library, make sure it was compiled with strings like "dex" and "header".

```bash
$ find venv -name "yara*.so"
venv/lib/python3.7/site-packages/yara_python-3.11.0-py3.7-macosx-10.14-x86_64.egg/yara.cpython-37m-darwin.so
```

Make sure it was compiled with `--enable-dex` by checking the strings.

```bash
$ strings venv/lib/python3.7/site-packages/yara_python-3.11.0-py3.7-macosx-10.14-x86_64.egg/yara.cpython-37m-darwin.so | grep '_dex'
_dex__declarations
_dex__finalize
_dex__initialize
_dex__load
_dex__unload
_dex_get_header
_dex_parse
_dex_parse_header
_dex__declarations
_dex_get_header
_dex_parse_header
_dex_parse
_dex__initialize
_dex__finalize
_dex__load
_dex__unload
```

Start python and check your load paths.

```python
>>> import sys
>>> print(sys.path)
['', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg', '/Users/caleb/repos/apkid/venv/lib/python3.7/site-packages/yara_python-3.11.0-py3.7-macosx-10.14-x86_64.egg', '/Users/caleb/repos/apkid']
```

Make sure that the yara module you confirmed has dex stuff in it is first in your load path.

My guess is you have something like yara installed (check with `pip freeze | grep yara`) that's put another version of the yara library in your load path, before the one with dex stuff.

Are you using virtualenv? If not, I suggest _always_ using it because I've spent so many days tracking down stupid dependency issues that arose because I had the wrong python module / ruby gem installed.
