### ISSUE TITLE
Add Kony "packer/protector"

### ISSUE THREAD

**Issue by strazzere** [rednaga/APKiD#22]
There is an SDK/IDE which "packs/protects" javascript based applications.

http://www.kony.com

**Comment by onthewater** [comment]
Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by circleous** [comment]
Any samples that i can try?

**Comment by strazzere** [comment]
You can build apps via the IDE which is free on the site. Others appear to be Southwest and other banking apps. If you look for the file `libkonyjsvm.so` it seems like a clear indicator of it's usage. Google searching this comes up with docs and some hits on different scanning services, ex;

https://www.virustotal.com/en/file/8c5a06348080237894a49324eda0d4229ab14eb382d3698bf63a528fa17db6b9/analysis/1475126425/

**Comment by strazzere** [comment]
Fixed in last commit
