### ISSUE TITLE
[Error] Support on Android (In Termux)

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#231]
Steps: 
1. Grab compiled arm/arm64 binary from https://github.com/atlantis0/arm-yara/tree/master/prebuilt 
2. Copy it in /data/data/com.termux/files/home/  and give it 777 permission so it can be accessed from termux terminal
3. Copy files from https://github.com/rednaga/APKiD/blob/master/apkid/rules/dex/ also to same location .
4 . Execute these command 
############################################################

  ./yara obfuscators.yara /sdcard/classes.dex 
output : 
/yara obfuscators.yara /sdcard/classes.dex      <
obfuscators.yara(165): warning in rule "dexguard_d": $a_if_class is slowing down scanning
obfuscators.yara(166): warning in rule "dexguard_d": $a_inner_unicode is slowing down scanning
obfuscators.yara(237): warning in rule "arxan": $m5 is slowing down scanning
obfuscators.yara(239): warning in rule "arxan": $m7 is slowing down scanning
obfuscators.yara(266): warning in rule "arxan_multidex": $m5 is slowing down scanning
obfuscators.yara(268): warning in rule "arxan_multidex": $m7 is slowing down scanning
is_dex /sdcard/classes.dex

Some things working but some giving such warning for /dex /elf /apk rules

**Comment by strazzere** [comment]
Few things here;

1. The rules are not meant to be run outside of APKiD - this is likely outside of the scope of any support you'll find on this repo / from anyone maintaining it.
2. The prebuilt binaries may not include the module we require? No idea, the source is not there
3. Nothing listed in your issue actually has an error

I'm closing this as invalid.
