### ISSUE TITLE
[DETECTION] Missed Dexprotector

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#238]
*Link Of file:*

https://play.google.com/store/apps/details?id=com.evozi.injector

*File:*
[HTTP Injector_5.0.9.apk.zip](https://github.com/rednaga/APKiD/files/5383690/HTTP.Injector_5.0.9.apk.zip)

MD5 : bae37effda45c26d36b0a6eb185feeaa
SHA1 : ded9b4d1c14e66dda06999e471729032a63ce32d

*Detection Issue *
Its expected to be detect as Dexprotector but it not detected

*Apk Files Layout *
assets/classes0.dex.dat
assets/classes1.dex.dat
assets/classes2.dex.dat
assets/dp.arm-v7.so.dat
assets/dp.arm-v8.so.dat
assets/dp.x86.so.dat
assets/dp.x86_x64.so.dat

**APKiD current results...**

$ apkid "HTTP Injector_5.0.9.apk"
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] HTTP Injector_5.0.9.apk!assets/audience_network.dex
 |-> anti_vm : possible Build.SERIAL check
 |-> compiler : unknown (please file detection issue!)
[*] HTTP Injector_5.0.9.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check
 |-> compiler : dx
 |-> obfuscator : unreadable field names, unreadable method names
$

**Comment by enovella** [comment]
It is detected:

```sh
[11:40 edu@xps ~] >  apkid ~/Downloads/HTTP.Injector_5.0.9.apk.zip 
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] /home/edu/Downloads/HTTP.Injector_5.0.9.apk.zip
 |-> packer : DexProtector
[*] /home/edu/Downloads/HTTP.Injector_5.0.9.apk.zip!assets/audience_network.dex
 |-> anti_vm : possible Build.SERIAL check
 |-> compiler : unknown (please file detection issue!)
[*] /home/edu/Downloads/HTTP.Injector_5.0.9.apk.zip!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check
 |-> compiler : dx
 |-> obfuscator : unreadable field names, unreadable method names
```
