### ISSUE TITLE
Add Arxan rules for native and dalvik obfuscation

### ISSUE THREAD

**Issue by strazzere** [rednaga/APKiD#24]
I've found what appears to be ITW samples of Arxan being used. Would be nice to fingerprint these, however it might be difficult as well since there doesn't seem to be any (straight forward) watermarking or branding.

**Comment by enovella** [comment]
Hi,

I've PR-ed a very basic rule for Dalvik obfuscation. Take a look at it

Cheers

**Comment by enovella** [comment]
Hi  @strazzere,

could  you close this issue due to my PR https://github.com/rednaga/APKiD/pull/50?

Cheers,

**Comment by strazzere** [comment]
Closed due to merge https://github.com/rednaga/APKiD/pull/50
