### ISSUE TITLE
[DETECTION] Hikari Obfuscator

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#241]
[Crackme03.apk.zip](https://github.com/rednaga/APKiD/files/5566412/Crackme03.apk.zip)

```sh
 [12:14 edu@xps Crackme03.apk.unpack] >  strings lib/armeabi-v7a/libarm_native.so|egrep -i "obfuscator|git|llvm"
 isxdigit
 /buildbot/src/android/ndk-release-r18/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp
 /buildbot/src/android/ndk-release-r18/external/libcxx/../../external/libunwind_llvm/src/UnwindCursor.hpp
 /buildbot/src/android/ndk-release-r18/external/libcxx/../../external/libunwind_llvm/src/Registers.hpp
 Android (4751641 based on r328903) clang version 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
 clang version 8.0.0 (tags/RELEASE_800/final) (https://gitee.com/chenzimo/Hikari.git ecdf30fa1a4635a76c3b528a41eb48d791f4be95)
```

```sh
$ apkid crackme03.apk
[+] APKiD 2.1.1 :: from RedNaga :: rednaga.io
[*] crackme03.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] crackme03.apk!classes2.dex
 |-> compiler : dexlib 2.x
```

The tool used in Obfuscation is
[Ultima_1.2.5.apk.zip](https://github.com/rednaga/APKiD/files/5566457/Ultima_1.2.5.apk.zip)
seems like Hakari obfuscator is used in this as backend

It have some paid features which support dex2c basic + ollvm and vmp basic + ollvm
above sample packed with vmp+ollvm

**Comment by enovella** [comment]
https://github.com/HikariObfuscator/Hikari

**Comment by apkunpacker** [comment]
[antisplitg2.apk.zip](https://github.com/rednaga/APKiD/files/5566630/antisplitg2.apk.zip)

**Comment by apkunpacker** [comment]
[Via.apk.zip](https://github.com/rednaga/APKiD/files/5567822/Via.apk.zip)
[NetShare.apk.zip](https://github.com/rednaga/APKiD/files/5567828/NetShare.apk.zip)

**Comment by enovella** [comment]
> This is VMP OLLVM
> [antisplitg2.apk.zip](https://github.com/rednaga/APKiD/files/5566630/antisplitg2.apk.zip)
> This is Dex2c OLLVM
> [antisplitg2(Dex2cOllvm).apk.zip](https://github.com/rednaga/APKiD/files/5566696/antisplitg2.Dex2cOllvm.apk.zip)

can you explain what is this?

**Comment by apkunpacker** [comment]
in that obfuscator 2 option . 1st is move dex class to native with dex2c with ollvm obfuscation and 2nd option is convert dex code to virtual machine code with ollvm obfuscation

**Comment by Ryonos** [comment]
You can create an apk with that two sources that you have ?

**Comment by apkunpacker** [comment]
> You can create an apk with that two sources that you have ?

All Attached files are already apk

**Comment by enovella** [comment]
```sh
[13:41 edu@xps hikari] >  apkid Crackme03.apk
[+] APKiD 2.1.2 :: from RedNaga :: rednaga.io
[*] Crackme03.apk!classes.dex
 |-> compiler : dexlib 2.x
[*] Crackme03.apk!classes2.dex
 |-> compiler : dexlib 2.x
[*] Crackme03.apk!lib/armeabi-v7a/libarm_native.so
 |-> obfuscator : Hikari
```
