### ISSUE TITLE
[FEATURE] Better Packaging.

### ISSUE THREAD

**Issue by ajinabraham** [rednaga/APKiD#246]
Would it make sense for APKiD authors to maintain dex-enabled yara-python as something like `yara-python-dex`, publish wheels to pypi and utilize it in apkid setup.py?
I am asking since the dex support is not available in yara-python upstream wheels on pypi.

A lot many users don't have sufficient developer setup or the knowledge to build yara-python. It would make their life easier. I use APKiD in MobSF and currently have to ship prebuilt wheels considering users without dev requirements.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/scripts/wheels

**Comment by CalebFenton** [comment]
It's not a bad idea assuming the yara-python team doesn't want to enable dex by default. The problem is that it's more work to maintain and keep up to date. If someone decides to create this dex enabled module and publish to pypi, I wouldn't mind changing requirements to point there.

**Comment by ajinabraham** [comment]
So I decided to create and maintain the dex enabled yara-python. 
Also send a PR: https://github.com/rednaga/APKiD/pull/247

**Comment by CalebFenton** [comment]
APKiD 2.1.2 pushed to pypi with this change. Installing is super easy now. Thanks again.

**Comment by ajinabraham** [comment]
Awesome! Closing this.
