### ISSUE TITLE
APKid not getting installed on Windows10 

### ISSUE THREAD

**Issue by KotamRamana** [rednaga/APKiD#26]
I have downloaded latest 0.9.5 Beta version from GIThub. I am planning to enable APKiD feature.
I have this installed on my laptop:
    1)Python 2.7.11
    2)VCForPython27

## STEPS TO REPRODUCE THE ISSUE
git clone https://github.com/rednaga/APKiD
cd APKiD
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install

## CONSOLE OUTPUT
C:\Users\********\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -Iyara/windows/include -IC:\Python27\include -IC:\Python27\PC /Tcyara\libyara\lexer.c /Fobuild\temp.win32-2.7\Release\yara\libyara\lexer.obj
lexer.c
lexer.l(794) : warning C4090: 'function' : different 'const' qualifiers
lexer.l(846) : error C2143: syntax error : missing ';' before 'type'
lexer.l(853) : error C2065: 'buf' : undeclared identifier
lexer.l(853) : warning C4022: 'ReadFile' : pointer mismatch for actual parameter 2
lexer.l(853) : error C2065: 'buf' : undeclared identifier
lexer.l(867) : error C2065: 'buf' : undeclared identifier
lexer.l(867) : warning C4047: 'function' : 'char *' differs in levels of indirection from 'int'
lexer.l(867) : warning C4024: 'yara_yy_scan_bytes' : different types for formal and actual parameter 1
error: command 'C:\\Users\\*********\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

## CONTENTS OF LOG FILES
NA

**Comment by strazzere** [comment]
Hey there @KotamRamana thanks for the report.

I currently do not have any access to a Windows box -- can you confirm that you're able to compile the normal yara-python on your machine? The errors you're displaying are inside code which we did not touch and I'm not familiar with what is going on.

Try installing this package, https://github.com/VirusTotal/yara-python - and see if you're still getting any errors. My guess is that if you can install that fine - the error is with our code. However if you're unable to install a "normal" yara-python, then there is an issue with your set up.

**Comment by KotamRamana** [comment]
HI Team,
Using command python setup.py build -->Error 1:D:\DevKit\APKiD\yara-python>python setup.py buildrunning buildrunning build_extbuilding 'yara' extensioncreating buildcreating build\temp.win32-2.7creating build\temp.win32-2.7\ReleaseC:\Users\********\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -Iyara/windows/include -IC:\Python27\include -IC:\Python27\PC /Tcyara-python.c /Fobuild\temp.win32-2.7\Release\yara-python.objyara-python.cyara-python.c(30) : fatal error C1083: Cannot open include file: 'yara.h': No such file or directoryerror: command 'C:\\Users\\**********\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2 Using command  pip install yara-python, I could install yara-python version 3.5.0.
Then I tried to install using command: pip install apkid. It failed due to dependency of yara-python.3.5.0.999.
Hence I edited setup.pynd made dependency to yara-python 3.5.0 and then ran:    python setup.py build    python setup.py install and finally installed apkid 1.0.0 version 
Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Saturday, May 13, 2017 1:24 AM, Tim Strazzere <notifications@github.com> wrote:
 

 Hey there @KotamRamana thanks for the report.I currently do not have any access to a Windows box -- can you confirm that you're able to compile the normal yara-python on your machine? The errors you're displaying are inside code which we did not touch and I'm not familiar with what is going on.Try installing this package, https://github.com/VirusTotal/yara-python - and see if you're still getting any errors. My guess is that if you can install that fine - the error is with our code. However if you're unable to install a "normal" yara-python, then there is an issue with your set up.—

**Comment by KotamRamana** [comment]
Hi Team,
When i use APKID following error:D:\DevKit\APKiD>apkid app-qabrta_24thApril.apk[+] APKiD 1.0.0 :: from RedNaga :: rednaga.ioTraceback (most recent call last):  File "C:\Python27\Scripts\apkid-script.py", line 11, in <module>    load_entry_point('apkid==1.0.0', 'console_scripts', 'apkid')()  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\__init__.py", line 60, in main    apkid.scan(input, args.timeout, args.json)  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\apkid.py", line 174, in scan    rules = get_rules()  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\apkid.py", line 83, in get_rules    return yara.load(rules_path)yara.Error: could not open file "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\rules/rules.yarc" Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Monday, May 15, 2017 10:43 AM, K.V.Ramanamurthy <kotam_ramana@yahoo.com> wrote:
 

 HI Team,
Using command python setup.py build -->Error 1:D:\DevKit\APKiD\yara-python>python setup.py buildrunning buildrunning build_extbuilding 'yara' extensioncreating buildcreating build\temp.win32-2.7creating build\temp.win32-2.7\ReleaseC:\Users\********\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -Iyara/windows/include -IC:\Python27\include -IC:\Python27\PC /Tcyara-python.c /Fobuild\temp.win32-2.7\Release\yara-python.objyara-python.cyara-python.c(30) : fatal error C1083: Cannot open include file: 'yara.h': No such file or directoryerror: command 'C:\\Users\\**********\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2 Using command  pip install yara-python, I could install yara-python version 3.5.0.
Then I tried to install using command: pip install apkid. It failed due to dependency of yara-python.3.5.0.999.
Hence I edited setup.pynd made dependency to yara-python 3.5.0 and then ran:    python setup.py build    python setup.py install and finally installed apkid 1.0.0 version 
Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Saturday, May 13, 2017 1:24 AM, Tim Strazzere <notifications@github.com> wrote:
 

 Hey there @KotamRamana thanks for the report.I currently do not have any access to a Windows box -- can you confirm that you're able to compile the normal yara-python on your machine? The errors you're displaying are inside code which we did not touch and I'm not familiar with what is going on.Try installing this package, https://github.com/VirusTotal/yara-python - and see if you're still getting any errors. My guess is that if you can install that fine - the error is with our code. However if you're unable to install a "normal" yara-python, then there is an issue with your set up.—

**Comment by strazzere** [comment]
It sounds like the specific version of yara-python we're using is not getting cloned as a submodule. I suggest you reread the instructions and see if it works. Or if the original VT version works. Closing for the time being as this seems stale.
