### ISSUE TITLE
yara.Error: could not map file "<data>" into memory

### ISSUE THREAD

**Issue by BerojgaarAadmi** [rednaga/APKiD#263]
Me install apkid in termux android
When I run apkid for any apk
apkid give this error
![Screenshot_20210502-005449_Termux](https://user-images.githubusercontent.com/64438196/116792895-1f095180-aae1-11eb-8625-d51ff14db35f.jpg)

**Comment by CalebFenton** [comment]
This is a yara error. APKiD is a clever set of rules and a wrapper around Yara, so this isn't surprising. You should raise this issue with the Yara team. Try and reproduce with only Yara and post an issue there.
