### ISSUE TITLE
[DETECTION] Promon Shield

### ISSUE THREAD

**Issue by dr0pd34d** [rednaga/APKiD#267]
**Provide the file**
APK can be downloaded here:
https://apkcombo.com/apk-downloader/?package=com.starfinanz.mobile.android.pushtan&device=default&arches=default&sdkInt=default&format=apk&dpi=480&lang=en
As of now the issue is based on **version 3.4.0**.

**Describe the detection issue**
The packer Promon Shield was expected to be detected.
The library should provide antidebug and more protections, but as the library is packed I do not know if detecting those would be possible.

**APKiD current results...**
```
$ apkid S-pushTAN_3.4.0.apk 
[+] APKiD 2.1.2 :: from RedNaga :: rednaga.io
[*] S-pushTAN_3.4.0.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check
 |-> compiler : dexlib 2.x
```

**Additional context**
As already talked about, the library now switched from using "lib.shield.XXXX.so" to the following "libenhefoocjfcl.so".
This seems to be a randomly generated filename.
As you mentioned they have stripped the symbols in the rule (crc32, inflate, ...) and the segments are the key to detect them.

**Comment by enovella** [comment]
```sh
[13:37 edu@xps APKiD-fork]  (master)>  apkid /tmp/s-pushtan_3.4.0.apk
[+] APKiD 2.1.2 :: from RedNaga :: rednaga.io
[*] /tmp/s-pushtan_3.4.0.apk!lib/arm64-v8a/libenhefoocjfcl.so
 |-> packer : Promon Shield
[*] /tmp/s-pushtan_3.4.0.apk!lib/armeabi-v7a/libenhefoocjfcl.so
 |-> packer : Promon Shield
[*] /tmp/s-pushtan_3.4.0.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check
 |-> compiler : dexlib 2.x
```
