### ISSUE TITLE
Docker is broken

### ISSUE THREAD

**Issue by dummys** [rednaga/APKiD#277]
Hi, the docker is broken ...

Removing intermediate container 6b55dfcbe349
 ---> 6609f2a29eb4
Step 6/14 : WORKDIR /apkid
 ---> Running in 0dac7a68c0a5
Removing intermediate container 0dac7a68c0a5
 ---> a9da71bda5dd
Step 7/14 : COPY . .
 ---> 0587fa9cbd31
Step 8/14 : RUN python prep-release.py &&     pip install -e .
 ---> Running in 2cd15ad672b0
[*] Compiling Yara files
[*] Saved 210 rules to /apkid/apkid/rules/rules.yarc
[*] Rules hash: a987c0ad561ae3c403d18cbaeb7dadc140aaac44bdb1a46da3082529874499b2
[*] Rule tag counts:
 |-> abnormal: 2
 |-> anti_debug: 1
 |-> anti_disassembly: 3
 |-> anti_vm: 28
 |-> compiler: 14
 |-> dropper: 2
 |-> embedded: 1
 |-> file_type: 3
 |-> internal: 19
 |-> manipulator: 1
 |-> obfuscator: 41
 |-> packer: 84
 |-> protector: 13
 |-> yara_issue: 1
[*] Finished preparing APKiD for release.
Obtaining file:///apkid
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement yara-python-dex>=1.0.0 (from apkid) (from versions: none)
ERROR: No matching distribution found for yara-python-dex>=1.0.0
The command '/bin/sh -c python prep-release.py &&     pip install -e .' returned a non-zero code: 1

btw not only docker, using virtualenv and pip is broken as well...

EDIT: I made it works using: `RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip wheel --quiet --no-cache-dir --wheel-dir=/tmp/yara-python-dex git+https://github.com/MobSF/yara-python-dex.git && \
    pip install --quiet --no-cache-dir --no-index --find-links=/tmp/yara-python-dex yara-python-dex && \
    rm -rf /tmp/yara-python-dex`

**Comment by enovella** [comment]
hi @dummys,

Thanks for opening a ticket. Also, I see you fixed it. Could you please open a pull-request with the potential fix for it?

Thanks

**Comment by dummys** [comment]
@enovella done: https://github.com/rednaga/APKiD/pull/278

**Comment by dummys** [comment]
fixed by caleb fix.
