### ISSUE TITLE
[DETECTION] JsonPacker

### ISSUE THREAD

**Issue by cryptax** [rednaga/APKiD#282]
Sample: https://koodous.com/apks/e23f0a124fdaba30c07a3c40011dd99240af081cec4cdfcb990c811126867e59

The sample is packed but this is not detected by APKiD yet:

**APKiD current results...**
```
$ apkid alien-jan2022.apk 
[+] APKiD 2.1.2 :: from RedNaga :: rednaga.io
[*] alien-jan2022.apk!classes.dex
 |-> anti_vm : Build.MANUFACTURER check
 |-> compiler : dexlib 2.x
```
I'd expect a "packer" line here. I don't have the official name for this packer. I've called it "JsonPacker", because it always contains JSON files (see below).

I'd like to add a detection rule for it in APKiD, but I'm a bit stuck at how to do it and would appreciate your help & integration in APKiD.

The packer extends the `Application` class, where it retrieves a special asset that contains an encrypted DEX. It decrypts it - using a proprietary algorithm (but not too complex) - and then loads it with `DexClassLoader`.
In the Yara rule, I believe we could check 

1. The **presence of the asset**. It's always a file named something.json. This part is easy for Yara :)
2. **Use of `DexClassLoader`**. This is no longer a APK rule but a DEX rule. I'm not sure we can mix?
3. We could possibly also **fingerprint the custom decryption algorithms**. They have junk code, but they always look alike, and basically boil down to an XOR. Same that's a DEX yara rule.

So far this is what I have. See below, the json file is always in the ./assets directory, and its name is usually a mixture of 3 to 5 alphabetic characters (mixing upper and lower case). This alone is perhaps a bit weak as a Yara rule, right?

```
rule jsonpacker : packer
{
   meta:
     description = "JsonPacker"
     sample       = "e23f0a124fdaba30c07a3c40011dd99240af081cec4cdfcb990c811126867e59"
     author        = "@cryptax and XXX"

   strings:
     $a1 = /assets\/[A-Za-z]{3,5}\.json/

   condition:
 // TODO
}
```

If you want to check the packer:

- the important class which extends `Application` is `com/core/course/XLbLiMkLySxTjPgFdTpAtHgOhWhGjZkSrPdLbAfCiJo`.
- the method which loads the DEX using `DexClassLoader` is `com/core/course/OXlNpRpBaPfJkOhOoNjYwJdPbDsAsKqOqOx.insanegasp`
- a typical decryption algorithm method is `com/core/course/XLbLiMkLySxTjPgFdTpAtHgOhWhGjZkSrPdLbAfCiJo.tiredlion`. You'll notice there is lots of junk code, but basically everything boils down to XORing the ciphertext `byte[] bArr = {40, 93, 35, 64, 47, 32, 38, 125, 35, 96};` with the key `byte[] bArr3 = {76, 14};`.

**Comment by cryptax** [comment]
So, I have come up with 2 different rules, 1 Yara APK rule and 1 Yara DEX rule. Is it possible to merge them somehow?

This the DEX rule:
```
include "common.yara"

rule jsonpacker : packer
{
   meta:
     description = "DexJsonPacker"
     sample       = "e23f0a124fdaba30c07a3c40011dd99240af081cec4cdfcb990c811126867e59"
     author        = "@cryptax and XXX"

   strings:
     $algo = {
       b0 9b da 0c 0b 00 b3 9c
       b0 1c b0 5c 93 05 06 06
       d8 05 05 ff b0 5c b4 66
       b0 6c 97 05 0c 0a
     }
     /*
         00288028: b09b                    006a: add-int/2addr       v11, v9
    0028802a: da0c 0b00               006b: mul-int/lit8        v12, v11, 0
    0028802e: b39c                    006d: div-int/2addr       v12, v9
    00288030: b01c                    006e: add-int/2addr       v12, v1
    00288032: b05c                    006f: add-int/2addr       v12, v5
    00288034: 9305 0606               0070: div-int             v5, v6, v6
    00288038: d805 05ff               0072: add-int/lit8        v5, v5, -1
    0028803c: b05c                    0074: add-int/2addr       v12, v5
    0028803e: b466                    0075: rem-int/2addr       v6, v6
    00288040: b06c                    0076: add-int/2addr       v12, v6
    00288042: 9705 0c0a               0077: xor-int             v5, v12, v10
    */
     $algo2 = {
        b0 c4 da 04 04 00 b0 94
	93 09 0c 0c b3 69 b7 69
	b0 94 94 09 0c 0c b0 94
	b7 b4
     }
     /*
     002fe1b2: b0c4                    005b: add-int/2addr       v4, v12
    002fe1b4: da04 0400               005c: mul-int/lit8        v4, v4, 0
    002fe1b8: b094                    005e: add-int/2addr       v4, v9
    002fe1ba: 9309 0c0c               005f: div-int             v9, v12, v12
    002fe1be: b369                    0061: div-int/2addr       v9, v6
    002fe1c0: b769                    0062: xor-int/2addr       v9, v6
    002fe1c2: b094                    0063: add-int/2addr       v4, v9
    002fe1c4: 9409 0c0c               0064: rem-int             v9, v12, v12
    002fe1c8: b094                    0066: add-int/2addr       v4, v9
    002fe1ca: b7b4                    0067: xor-int/2addr       v4, v11
    */
     
     $dexclass = {
       6e 20 ?? ?? 10 00 ?? ?? 1f 0b 
       // invoke-virtual      {v0, v1}, Ljava/lang/reflect/Constructor;->newInstance([Ljava/lang/Object;)Ljava/lang/Object;
       // check-cast          p1, Ldalvik/system/DexClassLoader; 
       }

   condition:
     is_dex
     and ($algo or $algo2)
     and $dexclass
}
```

This is the APK rule:
```
include "common.yara"

rule jsonpacker : packer
{
   meta:
     description = "ApkJsonPacker"
     sample       = "e23f0a124fdaba30c07a3c40011dd99240af081cec4cdfcb990c811126867e59"
     author        = "@cryptax and XXX"

   strings:
     $a1 = /assets\/[A-Za-z]{3,5}\.json/

   condition:
     is_apk
     and $a1

}
```

**Comment by enovella** [comment]
Hi @cryptax and XXX,

We could define a common rule in the APK folder, in `common.yara`:

```sh
rule has_json_in_assets : file_type
{
  meta:
    description = "JSON file in assets"

  strings:
    $json = /assets\/[A-Za-z]{3,5}\.json/

  condition:
    is_apk and $json 
}
```

Later, in DEX we can combine both rules to match your packer. Glad to review your PR.

```sh
   condition:
     is_dex and has_json_in_assets
     and ($algo or $algo2)
     and $dexclass
```

If you don't mind, please remove offsets from comments, and you can also mix bytecode with comments in the same variable:

```sh
    b0c4          // add-int/2addr       v4, v12
    da04 0400     // mul-int/lit8        v4, v4, 0
    b094          // add-int/2addr       v4, v9
    9309 0c0c     // div-int             v9, v12, v12
    b369          // div-int/2addr       v9, v6
    b769          // xor-int/2addr       v9, v6
    b094          // add-int/2addr       v4, v9
    9409 0c0c     // rem-int             v9, v12, v12
    b094          // add-int/2addr       v4, v9
    b7b4          // xor-int/2addr       v4, v11
```

**Comment by cryptax** [comment]
thanks @enovella - will do! I'm clean up and do a PR.

>@cryptax and XXX,

lol the XXX was meant to be you :)

**Comment by cryptax** [comment]
See pull request #284 for the solution I selected, and feel free to improve/edit. 
You can close the issue whenever this is ok to you.

**Comment by enovella** [comment]
merged https://github.com/rednaga/APKiD/pull/292
