### ISSUE TITLE
Cannot install APKiD

### ISSUE THREAD

**Issue by cryptax** [rednaga/APKiD#3]
I cannot perform the install of yara-python, and then I am unable to get apkid too.

Errors for yara-python:
```bash
$ python setup.py install
...
yara/libyara/modules/dex.c: In function ‘load_string_ids’:
yara/libyara/modules/dex.c:335:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0, p = 0; p < string_ids_size; i += 1, p += sizeof(STRING_ID_ITEM)) {
   ^
yara/libyara/modules/dex.c:335:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
yara/libyara/modules/dex.c: In function ‘load_type_ids’:
yara/libyara/modules/dex.c:371:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0, p = 0; p < type_ids_size; i += 1, p += sizeof(TYPE_ID_ITEM)) {

```

So, I tried to install yara-python without compilation using pip install yara-python. That succeeded.
Unfortunately, I cannot install apkid because yara-python is not the expected version it seems.

```bash
$ pip install apkid
Downloading/unpacking apkid
  Downloading apkid-0.9.3-py2.py3-none-any.whl
Downloading/unpacking yara-python==3.4.0.999 (from apkid)
  Could not find a version that satisfies the requirement yara-python==3.4.0.999 (from apkid) (from versions: 3.4.0.00)
Cleaning up...
No distributions matching the version for yara-python==3.4.0.999 (from apkid)
Storing debug log for failure in /tmp/tmpiZ98cv
```

My system:
- Linux Mint 17.3 Rosa
- yara-python 3.4.0.0

Additionally, I think it would be clearer in the install notes to modify:

```bash
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid
```

by this - to avoid confusion... :

```bash
git clone https://github.com/rednaga/APKiD
cd APKiD
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid
```

**Comment by strazzere** [comment]
Thanks Cryptax, I'm taking a look at this now. Pretty sure I know the issue and can fix it relatively fast. I'll try to patch this quickly 👍

**Comment by strazzere** [comment]
Ok as of; 
https://github.com/rednaga/yara-python/commit/88877e30b879c523c20f31f66de5ac328c43049e

Both the yara-python module and the yara module should updated with a fix that will correct the compilation errors you are having.

**Comment by strazzere** [comment]
Per the comment on instructions being unclear, I think I understand what you're saying now. So for the "installing" instructions, we're simply trying to clarify that to use `APKiD` currently you must install our modified `yara-python` project. This, hopefully, is only until the project is merged upstream into the master `yara-python` project. This is why we have you cloning only `yara-python` and not `APKiD`, followed by using `pip` to install our package.

Does this make sense? I'm going to try and reword the `README` to clarify this.

**Comment by strazzere** [comment]
With commit;
https://github.com/rednaga/APKiD/commit/9d7697ba8e4511449764c7038fc4012f54cd37c5
I believe I've address some clarity issues, let us know if there are any issues now. 👍

**Comment by cryptax** [comment]
Hi Tim, 

I had forgotten rednaga would go to you ;) Nice to "see" you again!

I'm afraid, I'm still having issues with compilation of yara-python. To be certain, I pulled a fresh repository for yara-python and apkid.

```
yara/libyara/modules/dex.c: In function ‘load_proto_ids’:
yara/libyara/modules/dex.c:429:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0, p = 0; p < proto_ids_size; i += 1, p += sizeof(PROTO_ID_ITEM)) {
   ^
yara/libyara/modules/dex.c:429:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
yara/libyara/modules/dex.c: In function ‘load_method_ids’:
yara/libyara/modules/dex.c:486:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0, p = 0; p < method_ids_size; i += 1, p += sizeof(METHOD_ID_ITEM)) {
   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I patched dex.c, with the following and then it compiled:

```c
int i, p;
for (i = 0, p = 0; p < proto_ids_size; i += 1, p += sizeof(PROTO_ID_ITEM)) {
```

It's strange because your modification in [rednaga/yara@6541005 ](https://github.com/rednaga/yara/commit/65410053ffb13d12eeea0a923f698b1141e2f67c) has the fix. But look [here](https://github.com/rednaga/yara/blob/master/libyara/modules/dex.c), the fix is not in. I haven't investigated why.

**Comment by rojaster** [comment]
Hi @cryptax , I've got the same error message. Looks like two lines 429 and 486 were not modified.
But with clang3.7.1 I built successfully and with GCC I caught this bug.

**Comment by cryptax** [comment]
yep, @rojaster I saw your bug report :)
