### ISSUE TITLE
[DETECTION] Unknown Ollvm Version

### ISSUE THREAD

**Issue by apkunpacker** [rednaga/APKiD#314]
File Link - https://virustotal.com/gui/file/2c720f5ec740f4c8571dbba205eadba483556c5c387fe88ff25192b25552da0f
File - 
[library.zip](https://github.com/rednaga/APKiD/files/9558458/library.zip)

APKiD Scan -
```sh
$ apkid library.zip
[+] APKiD 2.1.3 :: from RedNaga :: rednaga.io
[*] library.zip!optool.so
 |-> obfuscator : Obfuscator-LLVM version unknown
```
It should be detected Properly as Obfuscator-LLVM 8.0.0

```sh
$ strings library.so | grep Obfuscator
Obfuscator-LLVM clang version 8.0.0  (https://github.com/heroims/obfuscator.git 29d9dc8c1bd662f3a73d1b1b009266af1786b7b8) (based on Obfuscator-LLVM 8.0.0)
```
Repo link - https://github.com/heroims/obfuscator.git

**Comment by enovella** [comment]
can you open a pull-request with the fix? Its just copy paste another OLLVM rule.
