### ISSUE TITLE
code confusion

### ISSUE THREAD

**Issue by Shiuaier** [rednaga/APKiD#335]
I use jadx to open the apk and it shows that the code is confused, but apkid does not recognize the information about the code confusion.

```sh
$ apkid ./vip.invit.anna-29.apk 
[+] APKiD 2.1.4 :: from RedNaga :: rednaga.io
[*] ./vip.invit.anna-29.apk!classes.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, device ID check, emulator file check, network operator name check, possible Build.SERIAL check, possible VM check, ro.kernel.qemu check, ro.product.device check, subscriber ID check
 |-> compiler : r8
[*] ./vip.invit.anna-29.apk!classes2.dex
 |-> anti_vm : Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, emulator file check, possible Build.SERIAL check, possible ro.secure check, subscriber ID check
 |-> compiler : r8 without marker (suspicious)
[*] ./vip.invit.anna-29.apk!lib/armeabi-v7a/libAMapSDK_MAP_v6_9_0.so
 |-> packer : sharelib UPX
[*] ./vip.invit.anna-29.apk!lib/armeabi/libAMapSDK_MAP_v6_9_0.so
 |-> packer : sharelib UPX
```

![image](https://github.com/rednaga/APKiD/assets/133119482/af067599-cfb9-4da9-b175-d4037dde318a)

**Comment by Shiuaier** [comment]
> 

maybe,I don't know what obfuscation tool was used for this apk, but apkid didn't recognize it. Does apkid not recognize the apk obfuscated by ProGuard, why?

**Comment by CalebFenton** [comment]
Stripping function names is super common and it's nearly impossible to know what tool did it, at least with yara rules. I'm going to close this unless you think it's more than just remapping some identifiers. If someone can explain to me why this feature would be valuable, I'm open to doing it, but all of the approaches add significant complexity.
