### ISSUE TITLE
[DETECTION] Unknown lib packers

### ISSUE THREAD

**Issue by ghost** [rednaga/APKiD#336]
I encounted some modded APK that contained packed lib, that Apkid didnt detect. I barely can find any info about Android lib packers. Most modders using XMprotect, ollvm and UPX. Ollvm and Upx are detected by ApkID, and XM can be easly be identified so not a big deal for me.

Sample 1: libbmt.so is very large lib packer. Code section is short, OnLoad function is very large, making IDA fail to decompile it. I'm not sure whether OnLoad is obfuscted or they just put large data in it, but there are additional 5 mb of data not read by IDA

Apk: https://mega.nz/file/LAYEBIrT#BqojL9gWUxge6XidHHI0fnOvm_O30dpkfOMAKIt2zx0

Sample 2: libRMS.so is the small lib packer. Code section is short and simple without obfuscation. IDA throws an error "Unexpected attribute section format ('" when opening it but it can be igored

Apk: https://mega.nz/file/qVYD0IKC#MFsHhQxC6hm-IbMxKT6D3VAJ6CJp40__9gwXoiRgGK4

**Comment by enovella** [comment]
Thanks for the report, I will try to find time soon to take a crack at it. Any idea about the names or maintainers?
