### ISSUE TITLE
Apkid fails to analyse apk

### ISSUE THREAD

**Issue by Pertence** [rednaga/APKiD#34]
I can't analyse apk with the apkid command. By the way, I am using Windows 10 with and yara-python 3.6.3 from virustotal, because i couldn't install yara-python 3.5.0 from rednaga.

This is the output from the powershell terminal:
`[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io`
``Traceback (most recent call last):``
`` File "C:\Python27\Scripts\apkid-script.py", line 11, in <module>``
``   load_entry_point('apkid==1.0.0', 'console_scripts', 'apkid')()``
``  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\__init__.py", line 60, in main``
``    apkid.scan(input, args.timeout, args.json)``
``  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\apkid.py", line 174, in scan``
``    rules = get_rules()``
``  File "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\apkid.py", line 83, in get_rules``
``    return yara.load(rules_path)``
``yara.Error: could not open file "C:\Python27\lib\site-packages\apkid-1.0.0-py2.7.egg\apkid\rules/rules.yarc"``

Also, I have looked at folder and the is no such file.

**Comment by circleous** [comment]
Run `prep-release.py` to make Yara rules.

**Comment by CalebFenton** [comment]
If you don't install our fork of yara-python, you wont get our fork of yara, and you won't get the dex module and it won't work. It's unfortunate, but for now, you have to really follow the installation instructions.

**Comment by Pertence** [comment]
Thanks for the help. When I try to install this version of yara-python. I get this error:
´PS C:\Users\Augusto\Desktop\yara-python-master> python setup.py install
running install
running build
running build_ext
building 'yara' extension
C:\Users\Augusto\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /M
D /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -Iyara/window
s/include -IC:\Python27\include -IC:\Python27\PC /Tcyara-python.c /Fobuild\temp.win-amd64-2.7\Release\yara-python.obj
yara-python.c
yara-python.c(30) : fatal error C1083: Cannot open include file: 'yara.h': No such file or directory
error: command 'C:\\Users\\Augusto\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\am
d64\\cl.exe' failed with exit status 2´

**Comment by CalebFenton** [comment]
Does the official yara-python install for you? If not, then they'd be good people to ask / search for solution.

This looks like a problem installing yara-python on Windows in general. Tell me, does the `yara/` folder inside `yara-python-master` have files in it? Does the file `yara.h` exist?

**Comment by Pertence** [comment]
I can install the official version, but not the 3.5. Also, there is no yara.h in the yara folder.

**Comment by CalebFenton** [comment]
You can't install the official 3.5 version?

Does yara folder have files in it at all?

yara-python has the yara repo as a submodule. Normally, when you run `setup.py install` it pulls the submodule version. It could be that, because you're on Windows, something is going wrong. Do you have git installed?

```
╭─caleb@haxcalibur  ~/repos/yara-python/yara ‹› ‹master›
╰─$ find . | grep yara\.h
./libyara/include/yara/libyara.h
./libyara/include/yara.h
╭─caleb@haxcalibur  ~/repos/yara-python/yara ‹› ‹master›
╰─$ ls
AUTHORS       dist   libyara  windows       args.c       yarac.c      threading.h  README.md     build.sh
CONTRIBUTORS  docs   m4       configure.ac  threading.c  sample.file  yara.man     sample.rules  appveyor.yml
COPYING       extra  tests    Makefile.am   yara.c       args.h       yarac.man    bootstrap.sh
```

**Comment by Pertence** [comment]
I am using github app and I can see all the files on the folder, now.
When I try to run `python setup.py build` on yara-python folder.
I get this `running build
error: [Error 2] The system cannot find the file specified`
I have no problem on the 3.6 cloned from virustotal.

**Comment by CalebFenton** [comment]
You say you can see the files now, which implies you couldn't see them before. Please tell me what you did to change that.

The most important detail of the error is the actual name of the file which is missing. Please provide the full error including the missing file name.

Please manually confirm the file does not exist. Also, after building the official repo, confirm the file from your error exists there.

**Comment by Pertence** [comment]
I was downloading the zip from github website, now I cloned using the github app. Also, I will try to provide the full error, later.

**Comment by CalebFenton** [comment]
The zip of what? Our fork or the official repo?

**Comment by Pertence** [comment]
The official repo. Also, thanks for the help, but i decided to use apkid in the linux and its working. You can close this issue, if you wish.

**Comment by CalebFenton** [comment]
Thanks for the update. :D
