### ISSUE TITLE
Installation error - yara is not matching 

### ISSUE THREAD

**Issue by dineshdinz** [rednaga/APKiD#35]
I have followed the given step for installation but I am getting the below error while running "pip install aphid" I used mac.

" No matching distribution found for yara-python==3.5.0.999 (from aphid) "

Please help me on this......

**Comment by circleous** [comment]
Install `yara-python` from rednaga fork. rednaga/yara-python.

**Comment by strazzere** [comment]
@circleous is correct, you need to specifically install our fork. Also, that is a funny auto-correct on `apkid => aphid`

**Comment by dineshdinz** [comment]
yes, 
thanks for the update and i will check and update you all.
