### ISSUE TITLE
Yara Error: internal error 34

### ISSUE THREAD

**Issue by praseudo** [rednaga/APKiD#353]
Was facing below error at the time of executing the "apkid ~/path/example.apk" command.

└─$ apkid /home/kali/Downloads/kolesa.apk
[+] APKiD 2.1.1 :: from RedNaga :: rednaga.io
Exception scanning /home/kali/Downloads/kolesa.apk: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/apkid/apkid.py", line 123, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/apkid/apkid.py", line 139, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yara.Error: internal error: 34

**Comment by CalebFenton** [comment]
This error comes up a bit: https://github.com/search?q=repo%3Arednaga%2FAPKiD+yara.Error%3A+internal+error%3A+34&type=issues

It usually means you don't have the right dependencies installed. Check out the other issues with the same error message and see if the discussions help.
