### ISSUE TITLE
No matching distribution found for yara-python==3.5.0.999 (from aphid)

### ISSUE THREAD

**Issue by dineshdinz** [rednaga/APKiD#37]
Please make a installation video of apkid it will be useful for everyone

As mentioned I installed  yara-python from rednaga fork. https://github.com/rednaga/yara-python 
and I installed apkid using pip install apkid 

but still i am getting the same error like : 

""
#:yara-python spidi$ pip install apkid
Collecting apkid
  Using cached apkid-1.0.0-py2.py3-none-any.whl
Collecting argparse (from apkid)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting yara-python==3.5.0.999 (from apkid)
 ### Could not find a version that satisfies the requirement yara-python==3.5.0.999 (from apkid) (from versions: 3.4.0.0, 3.5.0, 3.6.0, 3.6.1, 3.6.2, 3.6.3)
No matching distribution found for yara-python==3.5.0.999 (from aphid)###
  ""

**Comment by strazzere** [comment]
I've tried the instructions last night on a clean machine and they worked for me...

If you run the following, what is the output?
```
$ pip list | grep yara
```

**Comment by circleous** [comment]
```
$ git clone --recursive https://github.com/rednaga/yara-python
$ cd yara-python
$ python setup.py build
$ sudo python setup.py install
```

**Comment by strazzere** [comment]
I believe this issue should be fixed assuming you can confirm you have followed @circleous steps and confirmed it has install via the step I've posted above.
