### ISSUE TITLE
openssl linking issue 

### ISSUE THREAD

**Issue by rromanen** [rednaga/APKiD#38]
While running a setup script I encountered this error indicating that I may be missing md5.h file in openssl: 
yara/libyara/modules/hash.c:30:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
^
1 error generated.
error: command 'cc' failed with exit status 1

I went ahead and found the file in question in /usr/local/Cellar/openssl/1.0.2l/include/openssl/md5.h

Then I tried to unlink/relink openssl with: brew unlink openssl && brew link openssl --force
After which I get the following warning refusing to link openssl:

"Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib"

Any clues on getting this to work? My hunch is that I am missing something with linking openssl for compiler to be able to see it?

**Comment by strazzere** [comment]
You could disable the module which requires crypto. I believe it is the hash module. So skimming the `setup.py` you likely could change:

```
      if building_for_windows:
        module.define_macros.append(('HASH_MODULE', '1'))
        module.libraries.append('libeay%s' % bits)
      elif (has_function('MD5_Init', libraries=['crypto']) and
          has_function('SHA256_Init', libraries=['crypto'])):
        module.define_macros.append(('HASH_MODULE', '1'))
        module.libraries.append('crypto')
      else:
        exclusions.append('yara/libyara/modules/hash.c')
```

to 

```
      exclusions.append('yara/libyara/modules/hash.c')
```

Thjat should remove the openssl requirement... I believe?

**Comment by strazzere** [comment]
Alternatively, you could refer to this issue on the original repo and the instructions someone has presented;

https://github.com/VirusTotal/yara-python/issues/17

**Comment by strazzere** [comment]
I'm going to close this as either approach listed above should solve the issues.
