### ISSUE TITLE
Add SafetyNet attestation detector rule

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#43]
Hi,

would it be nice to detect the use of Google SafetyNet to show "stealthy" behaviour? 
Although, it might not be useful for malware detection, it should be interesting.

Cheers

**Comment by CalebFenton** [comment]
For reference: https://developer.android.com/training/safetynet/index.html

What kind of stealthy behavior are you talking about? Trying to understand the value of this.

**Comment by enovella** [comment]
I'm considering to use your actual app to measure the robustness of the APK ( generally speaking & of course considering the amount of false positives).

In the same manner, we can try to detect whether there are anti-debugging, -rooting and -hooking countermeasures. Just an idea that it would make so happy for my daily work.

**Comment by CalebFenton** [comment]
I'm not familiar with SafetyNet. Does it have anti-debugging, anti-rooting, anti-hooking stuff? If so, it would make sense to add it to apkid.

I don't think apkid is the right place to add rules for detecting general robustness or code quality, however, but it may be worthwhile to look into an option like `--rules` to specify a file or folder with extra yara rules.

**Comment by enovella** [comment]
Hi Caleb,

As far as I remember from the last time I decompiled a SafetyNet package (`snet.jar` included in gms bundle), Google was checking for root binaries and don't remember if the debugger was checked (maybe it wasn't). Nowadays, they also check that the bootloader is unlocked (quite probable root is installed or not official ROM was installed). They also verify things like the SD, SSL, certificates,SELinux and many others. These days the `snet.jar` is obfuscated to prevent reverse-engineering and easy-to-bypass attempts. Take into account that SafetyNet is a constant OS-based attestation and not APP-based.

An example of oem unlocked bootloader:
```java
    static DeviceState getDeviceState() {
        DeviceState deviceState = new DeviceState();
        deviceState.verifiedBootState = systemPropertyStringValue("ro.boot.verifiedbootstate");
        deviceState.verityMode = systemPropertyStringValue("ro.boot.veritymode");
        deviceState.securityPatchLevel = systemPropertyStringValue("ro.build.version.security_patch");
        deviceState.oemUnlockSupported = systemPropertyIntValue("ro.oem_unlock_supported");
        deviceState.oemLocked = systemPropertyIntValue("ro.boot.flash.locked");
        return deviceState;
    }
````

I like the idea of implementing a new feature ( `--rules`) for my personal testing. Later on, we could discuss if these rules could be fit into APKiD in an extra rules folder or what-to-do with them.

Cheers
