### ISSUE TITLE
Improve DexGuard packer rule

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#44]
Hi,

some obfuscated APKs are not detected as DexGuard-ed. Could we improve the way of detecting it?

To be honest, I'm very new on Yara rules and so on, but you may know if it'd work the same detection like in [1] by using non-ASCII characters for this packer?

Best,

[1].- https://github.com/rednaga/APKiD/pull/42/commits/400467d41662e41ca784ea78f29a23c3b9e73539

**Comment by CalebFenton** [comment]
Please post the hashes of the DexGuarded samples that aren't being detected.

**Comment by enovella** [comment]
What about this one?
https://github.com/radare/radare2/issues/8679#issuecomment-336212154

```
$ apkid com.nostratech.gojek.driver_1.0.86.apk 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] com.nostratech.gojek.driver_1.0.86.apk!classes.dex
 |-> anti_disassembly : illegal class name
 |-> anti_vm : Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check
 |-> compiler : dexlib 2.x
```

**Comment by CalebFenton** [comment]
For reference, the sha256 is:

```
2dc4d374939973d47581652f069fecac5ca7ebd8233a803aa20dc4399fc6b922  com.nostratech.gojek.driver_1.0.86.apk
```

I can see the sample is heavily obfuscated. It would be nice if apkid could detect it. What makes you think it's DexGuard and not something else?

**Comment by enovella** [comment]
Thanks for investigating the sha256 hash.

Of course, I do not know which obfuscator is using. Though, what it makes me think that it is DexGuarded are the non-ASCII characters used for class renaming. These symbols seem to be used by this obfuscator. It is just an hypothesis but seems to be real.

**Comment by strazzere** [comment]
I'll attempt to tackle this one a bit later - however if someone can extract the class names which are non-ASCII characters first that'd be awesome. I wonder if they're part of #4

**Comment by enovella** [comment]
FYI, working on it.

**Comment by enovella** [comment]
Done in https://github.com/rednaga/APKiD/pull/123
