### ISSUE TITLE
Add ProGuard rule

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#45]
Hi,

It would be interesting to write a rule for detecting the default obfuscator "ProGuard".

Cheers

**Comment by strazzere** [comment]
The PR mentioned is for ApkGuard - is this the same as ProGuard? The site seems to be different and so does much of the actual changes...

**Comment by enovella** [comment]
Please look at  https://github.com/rednaga/APKiD/issues/41

**Comment by enovella** [comment]
Is anyone against detecting Proguard?

![proguard](https://user-images.githubusercontent.com/14809754/33288876-05996a3a-d3be-11e7-991a-df14cb62fe89.png)

**Comment by strazzere** [comment]
I don't think anyone is /against/ it - though it likely will be very noisy and overlapping.

Feel free to add it :)
