### ISSUE TITLE
Add obfuscator-llvm rules

### ISSUE THREAD

**Issue by strazzere** [rednaga/APKiD#5]
https://github.com/obfuscator-llvm/obfuscator

**Comment by circleous** [comment]
Just a rough guessing, medusah/appsolid libs are probably using O-LLVM since the control flow somewhat garbage-ish.

**Comment by strazzere** [comment]
You mean the native parts? Very likely -- it seems to be the most common native obfuscator (as it is free and just works) -- only other things I've seen are Arxan.

**Comment by enovella** [comment]
Hi Guys,

For the RadareCON 2017, I prepared  small challenge. This was an obfuscated binary with OLLVM and some weak anti-debugging and anti-hooking techniques. Looking for this string `Obfuscator-LLVM` could be a way.

```
[16:15 xxxx@xxxx r2con] > rabin2 -zzq antir2.hardened|grep -i llvm
0x2b 70 69 Obfuscator-LLVM clang version 4.0.1  (based on Obfuscator-LLVM 4.0.1)
```
Should I add a rule for that?

Cheers

**Comment by enovella** [comment]
Hi  @strazzere,

could  you close this issue due to my PR https://github.com/rednaga/APKiD/pull/47?

Cheers,

**Comment by strazzere** [comment]
Closed due to merge of https://github.com/rednaga/APKiD/pull/47
