### ISSUE TITLE
Broken on Python 3.6.1

### ISSUE THREAD

**Issue by jgrover** [rednaga/APKiD#57]
When running `apkid <apk>` in Python 3.6.1, I get the error: "AttributeError: module 'apkid' has no attribute 'scan'.

Everything seems to work fine when testing in Python 2.7.10.

**Comment by jgrover** [comment]
also, im running with pyenv.  Not sure if that makes a difference.

**Comment by strazzere** [comment]
Correct, there appears to be bugs in using anything over 2.7. I'll attempt to address this when I have time - unless someone else would like to assist.

**Comment by reox** [comment]
the thing is this: If you `import apkid`, you actually import apkid/__init__.py
this does not has scan of course... as you have the module apkid/apkid.py, you would need to say `import apkid.apkid` or follow http://python-future.org/compatible_idioms.html#imports-relative-to-a-package and use `from . import apkid`.

Not sure if this breaks stuff on other py versions - please test that ;) See the PR

**Comment by reox** [comment]
But does it work on py3 anyways? It starts, but I do not get any output for any file... The docker version seems to run fine.
