### ISSUE TITLE
New packer (possibly new version of APKGuard??)

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#71]
## Sample:
https://koodous.com/apks/673b3ab2e06f830e7ece1e3106a6a8c5f4bacd31393998fa73f6096b89f2df47

If anyone has some time to spend on, go ahead.

Backup: [673b3ab2e06f830e7ece1e3106a6a8c5f4bacd31393998fa73f6096b89f2df47.zip](https://github.com/rednaga/APKiD/files/1593972/673b3ab2e06f830e7ece1e3106a6a8c5f4bacd31393998fa73f6096b89f2df47.zip)

**Comment by enovella** [comment]
LOL :)

```c
    private static byte[] TYyhxVeTI(byte[] a, byte[] key) {
        byte[] out = new byte[a.length];
        for (int i = 0; i < a.length; i++) {
            out[i] = (byte) (a[i] ^ key[i % key.length]);
        }
        return out;
    }
```

**Comment by strazzere** [comment]
Confirmed after merging all other current PR's that nothing is hitting on this currently;

```
[36%]tstrazzere@beb0p:[~/repo/APKiD/docker] $ ./apkid.sh ~/Downloads/673b3ab2e06f830e7ece1e3106a6a8c5f4bacd31393998fa73f6096b89f2df47 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] 673b3ab2e06f830e7ece1e3106a6a8c5f4bacd31393998fa73f6096b89f2df47!classes.dex
 |-> compiler : dexlib 2.x
```

**Comment by enovella** [comment]
This is a new sample @strazzere !

**Comment by strazzere** [comment]
Yea, I figured. However I just wanted to ensure that all currently merged rules where or where not detected :)

**Comment by enovella** [comment]
More samples at
https://koodous.com/apks/80dbb245c8ff45356950acbf72d6e3ea4d842597c6e65202fb960d9a2a934f51
https://koodous.com/apks/005bd552d848c3675a4ba912a20dda2ceae83c08149e71798b89ca8d09266e27
https://koodous.com/apks/e34a2fa241070dd9787244f229de5519215c6afa58c68b67d6bb401576e40fa6

**Comment by enovella** [comment]
Done in PR https://github.com/rednaga/APKiD/pull/131
