### ISSUE TITLE
Reverse engineering Promon SHIELD at 34C3 conference

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#72]
Hey,

I was watching this talk when I thought that maybe APKiD did not include this protector. Many German banking apps are using it according to the author of the 34c3 talk.

**Talk:** https://media.ccc.de/v/34c3-8805-die_fabelhafte_welt_des_mobilebankings
(audio can be played in English if downloaded)
**Sample from the talk:** https://www.apkdownload.in/apk/app/com.starfinanz.yomo/

![promon](https://user-images.githubusercontent.com/14809754/34462795-a832002a-ee4b-11e7-9755-bde22484b66e.png)

**Info:** https://promon.co/
**Video:** https://www.youtube.com/watch?v=EoWLTEnddDI

Cheers

**Comment by enovella** [comment]
Done!

**Comment by P0r0** [comment]
Hello @enovella, just checked the last version of Starfinanz (https://github.com/P0r0/apksamples/blob/master/promonshield/com.starfinanz.mobile.android.pushtan_2018-08-15.apk). 

APKiD still can detect promonshield, however I noticed that the rule checks for the string "libshield.so" where this new version is more like "libshield.xxxxxx.so".

Even though the current rule is still able to detect PromonShield, would it be worth to add /libshield.(.*).so/ ?

**Comment by P0r0** [comment]
Moreover, I just read the paper you have shared https://www1.cs.fau.de/filepool/projects/nomorp/nomorp-paper-dimva2018.pdf and I noticed that the version of PromonShield that they have analysed uses some files located in assets/ directory

![a](https://user-images.githubusercontent.com/40885652/46200855-04f8a880-c313-11e8-8043-cca51f29c6ee.png)

is it worth to also add those files in the rule?

**Comment by enovella** [comment]
> Moreover, I just read the paper you have shared https://www1.cs.fau.de/filepool/projects/nomorp/nomorp-paper-dimva2018.pdf and I noticed that the version of PromonShield that they have analysed uses some files located in assets/ directory
> 
> ![a](https://user-images.githubusercontent.com/40885652/46200855-04f8a880-c313-11e8-8043-cca51f29c6ee.png)
> 
> is it worth to also add those files in the rule?

Yeah I realised about that some time ago but the rule was solid enough so I didnt care much. Feel free to improve it! ;)

**Comment by enovella** [comment]
> Hello @enovella, just checked the last version of Starfinanz (https://github.com/P0r0/apksamples/blob/master/promonshield/com.starfinanz.mobile.android.pushtan_2018-08-15.apk).
> 
> APKiD still can detect promonshield, however I noticed that the rule checks for the string "libshield.so" where this new version is more like "libshield.xxxxxx.so".
> 
> Even though the current rule is still able to detect PromonShield, would it be worth to add /libshield.(.*).so/ ?

Yes and no. This line represents the string in the ELF file:
https://github.com/rednaga/APKiD/blob/master/apkid/rules/elf/packers.yara#L325

Notice that this rule doesn't make use of `is_apk` so it doesn't search for library names but looks inside the ELF file. That's why you only got the match at the ELF level and not at the APK level (as all the other rules do).

We can improve it with your new research :)

**Comment by enovella** [comment]
Cloned your repository and tested the sample you mentioned:
```
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!classes.dex
 |-> anti_disassembly : illegal class name
 |-> compiler : dexlib 2.x
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!lib/x86/libshield.06604240.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!lib/armeabi-v7a/libshield.06604240.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk
```

We can create the Promon rule at the APK level instead of matching all native libs. What do you think guys? @CalebFenton @strazzere

**Comment by enovella** [comment]
There are new samples that aren't matching our rule. Don't have the time to update it.

**Comment by strazzere** [comment]
Can you... Add those samples / hashes?

**Comment by CalebFenton** [comment]
@strazzere the sample is hiding in an older comment -- https://github.com/P0r0/apksamples/blob/master/promonshield/com.starfinanz.mobile.android.pushtan_2018-08-15.apk
And the sha256 is 636d4216f5e397b9ac5d824d611db1b2a69f2245370fce5b4f947edc26dee558


> Even though the current rule is still able to detect PromonShield, would it be worth to add /libshield.(.*).so/ ?

If a new version changed the lib name, I think it's good to detect it as a new rule with a new variant name. So the original one becomes "promon_a" and the new rule is "promon_b".

And as whether or not to detect at the ELF of APK level, it's always preferable to detect the specific artifacts affected by obfuscation. For example, if Promon is an elf obfuscator, it's best to write signatures for the elf files. This is because _APKiD isn't always run on APKs_. It may be run against a directory of elf files, and if our only signatures are against the APK, we won't ID them correctly. Sometimes writing signatures is hard but it's almost never impossible.

If you acquire enough of the obfuscated elf files, it may be possible to use some generic signature generation tools that exist, and if a tool like that isn't forthcoming, I have one we can try.

**Comment by strazzere** [comment]
@CalebFenton Ah, I totally didn't read the full details on that. Also, agreed with your comments, would be excellent to profile the actual obfuscation/elf file, etc - vs just the naming.

**Comment by enovella** [comment]
> @strazzere the sample is hiding in an older comment -- https://github.com/P0r0/apksamples/blob/master/promonshield/com.starfinanz.mobile.android.pushtan_2018-08-15.apk
> And the sha256 is 636d4216f5e397b9ac5d824d611db1b2a69f2245370fce5b4f947edc26dee558

This is detected ;) I will add soon a sample of possibly a newer version.
```
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!classes.dex
 |-> anti_disassembly : illegal class name
 |-> compiler : dexlib 2.x
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!lib/armeabi-v7a/libshield.06604240.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk!lib/x86/libshield.06604240.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] com.starfinanz.mobile.android.pushtan_2018-08-15.apk
```

> > Even though the current rule is still able to detect PromonShield, would it be worth to add /libshield.(.*).so/ ?

Several things changed. Indeed the lib name and config files.


> If a new version changed the lib name, I think it's good to detect it as a new rule with a new variant name. So the original one becomes "promon_a" and the new rule is "promon_b".

Perfect!

> And as whether or not to detect at the ELF of APK level, it's always preferable to detect the specific artifacts affected by obfuscation. For example, if Promon is an elf obfuscator, it's best to write signatures for the elf files. This is because _APKiD isn't always run on APKs_. It may be run against a directory of elf files, and if our only signatures are against the APK, we won't ID them correctly. Sometimes writing signatures is hard but it's almost never impossible.

Totally agree. Promon is a packer and/or obfuscator (although it uses OLLVM underneath)

**Comment by enovella** [comment]
I think that @P0r0 was wrong with the comment of the library. There were indeed several strings to make rules with. For instance, at ELF level the string `libshield.so` was buried within the binary (not anymore?). At APK level, we had the `libshield.xxxxxx.so` where `xxxxxx` should be the git version. All this is an hypothesis though.

**Comment by enovella** [comment]
Basically, you could create a rule at APK level with `libshield.xxxxxx.so` and the assets `mappings.bin` + `pbi.bin` + `config-encrypt.txt`.

![img](https://user-images.githubusercontent.com/40885652/46200855-04f8a880-c313-11e8-8043-cca51f29c6ee.png)

**Comment by strazzere** [comment]
This appears to have been fixed already, promon shield is properly detected AFAIK.

**Comment by enovella** [comment]
There are changes in the newer versions. Please leave it opened to remember to myself that I must do it.

**Comment by enovella** [comment]
Also, I am not happy with the rule I wrote some time ago.......

**Comment by enovella** [comment]
```sh
promon-packer] >  apkid de.fiducia.smartphone.android.securego.vr.apk
[+] APKiD 1.2.1 :: from RedNaga :: rednaga.io
[*] de.fiducia.smartphone.android.securego.vr.apk!classes.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, possible Build.SERIAL check
 |-> compiler : dexlib 2.x
[*] de.fiducia.smartphone.android.securego.vr.apk!lib/x86/libgiompappkhnb.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
[*] de.fiducia.smartphone.android.securego.vr.apk!lib/armeabi-v7a/libgiompappkhnb.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
[*] de.fiducia.smartphone.android.securego.vr.apk
```

**Comment by enovella** [comment]
Missed
```sh
[14:28 edu@xps ~] >  apkid Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk 
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!classes.dex
 |-> anti_vm : Build.MANUFACTURER check, possible Build.SERIAL check
 |-> compiler : dexlib 2.x
[*] Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/arm64-v8a/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
[*] Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/x86/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
[*] Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/armeabi-v7a/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
```

**Comment by saeed9321** [comment]
From iOS prospective I was just trying yesterday hooking memcyp after reading the below.

![1](https://user-images.githubusercontent.com/38338100/121300641-2c97cf80-c908-11eb-89f5-3687758f10a1.JPG)

I was not able to get any releavant string to jailbreak, debugger, config ...etc

What is the best approach to overcome/bypass this shield ?

**Comment by enovella** [comment]
> ```shell
> apkid Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk 
> ```

```sh
[10:17 edu@xps ~] >  apkid ~/Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk 
[+] APKiD 2.1.2 :: from RedNaga :: rednaga.io
[*] /home/edu/Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!classes.dex
 |-> anti_vm : Build.MANUFACTURER check, possible Build.SERIAL check
 |-> compiler : dexlib 2.x
[*] /home/edu/Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/arm64-v8a/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] /home/edu/Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/x86/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
[*] /home/edu/Downloads/cf44e77e11cdcc7c3dc2a4112c369a2fac1637fa757b958302df4291f81aa1de.apk!lib/armeabi-v7a/libejmfnmkjdmph.so
 |-> obfuscator : Obfuscator-LLVM version 3.5
 |-> packer : Promon Shield
```

**Comment by enovella** [comment]
@saeed9321 We only do INTEL here
