### ISSUE TITLE
Add rule for ADVobfuscator

### ISSUE THREAD

**Issue by strazzere** [rednaga/APKiD#80]
https://github.com/andrivet/ADVobfuscator

Looks like Secneo/Bangcle may use this under the hood as well.

**Comment by enovella** [comment]
To take a look at symbols: `ObfuscatedCall` `ObfuscatedAddress`

**Comment by enovella** [comment]
Done! I will pull-request it soon.

**Comment by strazzere** [comment]
Done elsewhere, thanks @enovella
