### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by pat-ford** [rednaga/APKiD#85]
Hi All;
 I followed the directions on readme.md. when I got to the last step:
`~/git/yara-python$ pip install apkid
Collecting apkid
  Using cached apkid-1.0.0-py2.py3-none-any.whl
Collecting argparse (from apkid)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting yara-python==3.5.0.999 (from apkid)
  Could not find a version that satisfies the requirement yara-python==3.5.0.999 (from apkid) (from versions: 3.4.0.0, 3.5.0, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.7.0)
No matching distribution found for yara-python==3.5.0.999 (from apkid)
`

I'm going to poke around but thought I'd post here as a reminder.
Pat

**Comment by strazzere** [comment]
Did you install our fork of `yara-python` first?

Alternatively, the docker version should "just work".

**Comment by pat-ford** [comment]
Hey Diff; 
I went step by step;
`git clone --recursive https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid`

Right now I'm trying `python3 setup.py install`

**Comment by pat-ford** [comment]
I'll do the docker thing tomorrow, good night all!

**Comment by strazzere** [comment]
My guess is that you're running multiple versions of `python` in those commands. I suggest not using `python3` currently - as it may fail.

Anyone, specifically you're doing;
`python setup.py install`
^- check what environment that is getting installed too (my guess is not `python3`).

Also ensure that `pip` is hitting the same env.

**Comment by CalebFenton** [comment]
Try using a virtualenv to ensure there's no conflicting other versions, and +1 to what @strazzere said.
