### ISSUE TITLE
[DRAFT] Changelog new release

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#96]
This is a draft to take into account for the upcoming release of APKiD. It might be incomplete at the moment and new protectors can be added.

## Native obfuscators
- Obfuscator-LLVM 
  - v3.4
  - v3.5
  - v3.6.1
  - v4.0
  - v6.0 (unofficial fork)
  - v6.0 with string encryption (unofficial fork)
  - version-less
- Firehash
- AVDobfuscator

## DEX obfuscators
- Allatori demo 
- Arxan
  - Multidex support
- DexProtector (bugfixes)
- AAMO (**A**nother **A**ndroid **M**alware **O**bfuscator)

## Native packers
- Promon Shield
- UPX
  - v3.93
  - v3.94
- Bangcle SecShell (secneo-like)
- AppGuard (secneo-like)

## DEX packers
- ApkPacker (Custom packer)
- CryptoShell
- ApkGuard
- DexProtector (more versions)
- Jiagu (ApkToolPlus)
- Custom Chinese ChornClickers (**Ch**-ina P**ornClickers**)

**Comment by CalebFenton** [comment]
Thanks for maintaining this list. I'm closing it now since the release has been published.
